-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1d_top is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC );
end;


architecture behav of fft_1d_top is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "fft_1d_top_fft_1d_top,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-2,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.869100,HLS_SYN_LAT=8339,HLS_SYN_TPT=5255,HLS_SYN_MEM=15,HLS_SYN_DSP=0,HLS_SYN_FF=10691,HLS_SYN_LUT=8903,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_bufI_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_bufI_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_bufQ_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_bufQ_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_bufI_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_bufI_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_bufQ_i_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_bufQ_t_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal scaling_schedule : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_scaling_schedule_c_din : STD_LOGIC_VECTOR (31 downto 0);
    signal entry_proc_U0_scaling_schedule_c_write : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_ap_start : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_ap_done : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_ap_continue : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_ap_idle : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_ap_ready : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_stream_TREADY : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufI_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Block_entry_in_bufI_wr_proc_U0_in_bufI_ce1 : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufI_we1 : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufI_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Block_entry_in_bufI_wr_proc_U0_in_bufQ_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal Block_entry_in_bufI_wr_proc_U0_in_bufQ_ce1 : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufQ_we1 : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufQ_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_in_bufQ : STD_LOGIC;
    signal Block_entry_in_bufI_wr_proc_U0_in_bufQ_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_in_bufQ : STD_LOGIC := '0';
    signal ap_sync_channel_write_in_bufQ : STD_LOGIC;
    signal stage_process_fft_real_U0_ap_start : STD_LOGIC;
    signal stage_process_fft_real_U0_ap_done : STD_LOGIC;
    signal stage_process_fft_real_U0_ap_continue : STD_LOGIC;
    signal stage_process_fft_real_U0_ap_idle : STD_LOGIC;
    signal stage_process_fft_real_U0_ap_ready : STD_LOGIC;
    signal stage_process_fft_real_U0_scaling_schedule_read : STD_LOGIC;
    signal stage_process_fft_real_U0_in_bufI_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_process_fft_real_U0_in_bufI_ce0 : STD_LOGIC;
    signal stage_process_fft_real_U0_in_bufQ_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_process_fft_real_U0_in_bufQ_ce0 : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufI_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_process_fft_real_U0_out_bufI_ce1 : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufI_we1 : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufI_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal stage_process_fft_real_U0_out_bufQ_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_process_fft_real_U0_out_bufQ_ce1 : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufQ_we1 : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufQ_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_channel_done_out_bufQ : STD_LOGIC;
    signal stage_process_fft_real_U0_out_bufQ_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_out_bufQ : STD_LOGIC := '0';
    signal ap_sync_channel_write_out_bufQ : STD_LOGIC;
    signal stage_write_output_U0_ap_start : STD_LOGIC;
    signal stage_write_output_U0_ap_done : STD_LOGIC;
    signal stage_write_output_U0_ap_continue : STD_LOGIC;
    signal stage_write_output_U0_ap_idle : STD_LOGIC;
    signal stage_write_output_U0_ap_ready : STD_LOGIC;
    signal stage_write_output_U0_outI_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_write_output_U0_outI_ce0 : STD_LOGIC;
    signal stage_write_output_U0_outQ_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal stage_write_output_U0_outQ_ce0 : STD_LOGIC;
    signal stage_write_output_U0_out_stream_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal stage_write_output_U0_out_stream_TVALID : STD_LOGIC;
    signal stage_write_output_U0_out_stream_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal stage_write_output_U0_out_stream_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal stage_write_output_U0_out_stream_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal stage_write_output_U0_out_stream_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal stage_write_output_U0_out_stream_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal stage_write_output_U0_out_stream_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal in_bufI_i_full_n : STD_LOGIC;
    signal in_bufI_t_empty_n : STD_LOGIC;
    signal in_bufQ_i_full_n : STD_LOGIC;
    signal in_bufQ_t_empty_n : STD_LOGIC;
    signal out_bufI_i_full_n : STD_LOGIC;
    signal out_bufI_t_empty_n : STD_LOGIC;
    signal out_bufQ_i_full_n : STD_LOGIC;
    signal out_bufQ_t_empty_n : STD_LOGIC;
    signal scaling_schedule_c_full_n : STD_LOGIC;
    signal scaling_schedule_c_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal scaling_schedule_c_empty_n : STD_LOGIC;
    signal scaling_schedule_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal scaling_schedule_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_entry_in_bufI_wr_proc_U0_ap_ready : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1d_top_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        scaling_schedule : IN STD_LOGIC_VECTOR (31 downto 0);
        scaling_schedule_c_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        scaling_schedule_c_full_n : IN STD_LOGIC;
        scaling_schedule_c_write : OUT STD_LOGIC;
        scaling_schedule_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        scaling_schedule_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component fft_1d_top_Block_entry_in_bufI_wr_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufI_ce1 : OUT STD_LOGIC;
        in_bufI_we1 : OUT STD_LOGIC;
        in_bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        in_bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufQ_ce1 : OUT STD_LOGIC;
        in_bufQ_we1 : OUT STD_LOGIC;
        in_bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_stage_process_fft_real IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        scaling_schedule_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        scaling_schedule_empty_n : IN STD_LOGIC;
        scaling_schedule_read : OUT STD_LOGIC;
        scaling_schedule_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        scaling_schedule_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        in_bufI_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufI_ce0 : OUT STD_LOGIC;
        in_bufI_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        in_bufQ_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufQ_ce0 : OUT STD_LOGIC;
        in_bufQ_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        out_bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_bufI_ce1 : OUT STD_LOGIC;
        out_bufI_we1 : OUT STD_LOGIC;
        out_bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_bufQ_ce1 : OUT STD_LOGIC;
        out_bufQ_we1 : OUT STD_LOGIC;
        out_bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_stage_write_output IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_stream_TREADY : IN STD_LOGIC;
        outI_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        outI_ce0 : OUT STD_LOGIC;
        outI_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        outQ_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        outQ_ce0 : OUT STD_LOGIC;
        outQ_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        out_stream_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_stream_TVALID : OUT STD_LOGIC;
        out_stream_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        out_stream_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        out_stream_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fft_1d_top_in_bufI_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        i_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        i_ce0 : IN STD_LOGIC;
        i_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        i_ce1 : IN STD_LOGIC;
        i_we1 : IN STD_LOGIC;
        i_d1 : IN STD_LOGIC_VECTOR (15 downto 0);
        t_address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        t_ce0 : IN STD_LOGIC;
        t_q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        t_address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        t_ce1 : IN STD_LOGIC;
        t_we1 : IN STD_LOGIC;
        t_d1 : IN STD_LOGIC_VECTOR (15 downto 0);
        i_ce : IN STD_LOGIC;
        t_ce : IN STD_LOGIC;
        i_full_n : OUT STD_LOGIC;
        i_write : IN STD_LOGIC;
        t_empty_n : OUT STD_LOGIC;
        t_read : IN STD_LOGIC );
    end component;


    component fft_1d_top_fifo_w32_d3_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component fft_1d_top_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        scaling_schedule : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;



begin
    in_bufI_U : component fft_1d_top_in_bufI_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => ap_const_lv10_0,
        i_ce0 => ap_const_logic_0,
        i_q0 => in_bufI_i_q0,
        i_address1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_address1,
        i_ce1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_ce1,
        i_we1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_we1,
        i_d1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_d1,
        t_address0 => stage_process_fft_real_U0_in_bufI_address0,
        t_ce0 => stage_process_fft_real_U0_in_bufI_ce0,
        t_q0 => in_bufI_t_q0,
        t_address1 => ap_const_lv10_0,
        t_ce1 => ap_const_logic_0,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv16_0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => in_bufI_i_full_n,
        i_write => ap_channel_done_in_bufQ,
        t_empty_n => in_bufI_t_empty_n,
        t_read => stage_process_fft_real_U0_ap_ready);

    in_bufQ_U : component fft_1d_top_in_bufI_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => ap_const_lv10_0,
        i_ce0 => ap_const_logic_0,
        i_q0 => in_bufQ_i_q0,
        i_address1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_address1,
        i_ce1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_ce1,
        i_we1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_we1,
        i_d1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_d1,
        t_address0 => stage_process_fft_real_U0_in_bufQ_address0,
        t_ce0 => stage_process_fft_real_U0_in_bufQ_ce0,
        t_q0 => in_bufQ_t_q0,
        t_address1 => ap_const_lv10_0,
        t_ce1 => ap_const_logic_0,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv16_0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => in_bufQ_i_full_n,
        i_write => ap_channel_done_in_bufQ,
        t_empty_n => in_bufQ_t_empty_n,
        t_read => stage_process_fft_real_U0_ap_ready);

    out_bufI_U : component fft_1d_top_in_bufI_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => ap_const_lv10_0,
        i_ce0 => ap_const_logic_0,
        i_q0 => out_bufI_i_q0,
        i_address1 => stage_process_fft_real_U0_out_bufI_address1,
        i_ce1 => stage_process_fft_real_U0_out_bufI_ce1,
        i_we1 => stage_process_fft_real_U0_out_bufI_we1,
        i_d1 => stage_process_fft_real_U0_out_bufI_d1,
        t_address0 => stage_write_output_U0_outI_address0,
        t_ce0 => stage_write_output_U0_outI_ce0,
        t_q0 => out_bufI_t_q0,
        t_address1 => ap_const_lv10_0,
        t_ce1 => ap_const_logic_0,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv16_0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => out_bufI_i_full_n,
        i_write => ap_channel_done_out_bufQ,
        t_empty_n => out_bufI_t_empty_n,
        t_read => stage_write_output_U0_ap_ready);

    out_bufQ_U : component fft_1d_top_in_bufI_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        i_address0 => ap_const_lv10_0,
        i_ce0 => ap_const_logic_0,
        i_q0 => out_bufQ_i_q0,
        i_address1 => stage_process_fft_real_U0_out_bufQ_address1,
        i_ce1 => stage_process_fft_real_U0_out_bufQ_ce1,
        i_we1 => stage_process_fft_real_U0_out_bufQ_we1,
        i_d1 => stage_process_fft_real_U0_out_bufQ_d1,
        t_address0 => stage_write_output_U0_outQ_address0,
        t_ce0 => stage_write_output_U0_outQ_ce0,
        t_q0 => out_bufQ_t_q0,
        t_address1 => ap_const_lv10_0,
        t_ce1 => ap_const_logic_0,
        t_we1 => ap_const_logic_0,
        t_d1 => ap_const_lv16_0,
        i_ce => ap_const_logic_1,
        t_ce => ap_const_logic_1,
        i_full_n => out_bufQ_i_full_n,
        i_write => ap_channel_done_out_bufQ,
        t_empty_n => out_bufQ_t_empty_n,
        t_read => stage_write_output_U0_ap_ready);

    CTRL_s_axi_U : component fft_1d_top_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        scaling_schedule => scaling_schedule,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    entry_proc_U0 : component fft_1d_top_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        scaling_schedule => scaling_schedule,
        scaling_schedule_c_din => entry_proc_U0_scaling_schedule_c_din,
        scaling_schedule_c_full_n => scaling_schedule_c_full_n,
        scaling_schedule_c_write => entry_proc_U0_scaling_schedule_c_write,
        scaling_schedule_c_num_data_valid => scaling_schedule_c_num_data_valid,
        scaling_schedule_c_fifo_cap => scaling_schedule_c_fifo_cap);

    Block_entry_in_bufI_wr_proc_U0 : component fft_1d_top_Block_entry_in_bufI_wr_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_entry_in_bufI_wr_proc_U0_ap_start,
        ap_done => Block_entry_in_bufI_wr_proc_U0_ap_done,
        ap_continue => Block_entry_in_bufI_wr_proc_U0_ap_continue,
        ap_idle => Block_entry_in_bufI_wr_proc_U0_ap_idle,
        ap_ready => Block_entry_in_bufI_wr_proc_U0_ap_ready,
        in_stream_TDATA => in_stream_TDATA,
        in_stream_TVALID => in_stream_TVALID,
        in_stream_TREADY => Block_entry_in_bufI_wr_proc_U0_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP,
        in_stream_TSTRB => in_stream_TSTRB,
        in_stream_TUSER => in_stream_TUSER,
        in_stream_TLAST => in_stream_TLAST,
        in_stream_TID => in_stream_TID,
        in_stream_TDEST => in_stream_TDEST,
        in_bufI_address1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_address1,
        in_bufI_ce1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_ce1,
        in_bufI_we1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_we1,
        in_bufI_d1 => Block_entry_in_bufI_wr_proc_U0_in_bufI_d1,
        in_bufQ_address1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_address1,
        in_bufQ_ce1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_ce1,
        in_bufQ_we1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_we1,
        in_bufQ_d1 => Block_entry_in_bufI_wr_proc_U0_in_bufQ_d1);

    stage_process_fft_real_U0 : component fft_1d_top_stage_process_fft_real
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => stage_process_fft_real_U0_ap_start,
        ap_done => stage_process_fft_real_U0_ap_done,
        ap_continue => stage_process_fft_real_U0_ap_continue,
        ap_idle => stage_process_fft_real_U0_ap_idle,
        ap_ready => stage_process_fft_real_U0_ap_ready,
        scaling_schedule_dout => scaling_schedule_c_dout,
        scaling_schedule_empty_n => scaling_schedule_c_empty_n,
        scaling_schedule_read => stage_process_fft_real_U0_scaling_schedule_read,
        scaling_schedule_num_data_valid => scaling_schedule_c_num_data_valid,
        scaling_schedule_fifo_cap => scaling_schedule_c_fifo_cap,
        in_bufI_address0 => stage_process_fft_real_U0_in_bufI_address0,
        in_bufI_ce0 => stage_process_fft_real_U0_in_bufI_ce0,
        in_bufI_q0 => in_bufI_t_q0,
        in_bufQ_address0 => stage_process_fft_real_U0_in_bufQ_address0,
        in_bufQ_ce0 => stage_process_fft_real_U0_in_bufQ_ce0,
        in_bufQ_q0 => in_bufQ_t_q0,
        out_bufI_address1 => stage_process_fft_real_U0_out_bufI_address1,
        out_bufI_ce1 => stage_process_fft_real_U0_out_bufI_ce1,
        out_bufI_we1 => stage_process_fft_real_U0_out_bufI_we1,
        out_bufI_d1 => stage_process_fft_real_U0_out_bufI_d1,
        out_bufQ_address1 => stage_process_fft_real_U0_out_bufQ_address1,
        out_bufQ_ce1 => stage_process_fft_real_U0_out_bufQ_ce1,
        out_bufQ_we1 => stage_process_fft_real_U0_out_bufQ_we1,
        out_bufQ_d1 => stage_process_fft_real_U0_out_bufQ_d1);

    stage_write_output_U0 : component fft_1d_top_stage_write_output
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => stage_write_output_U0_ap_start,
        ap_done => stage_write_output_U0_ap_done,
        ap_continue => stage_write_output_U0_ap_continue,
        ap_idle => stage_write_output_U0_ap_idle,
        ap_ready => stage_write_output_U0_ap_ready,
        out_stream_TREADY => out_stream_TREADY,
        outI_address0 => stage_write_output_U0_outI_address0,
        outI_ce0 => stage_write_output_U0_outI_ce0,
        outI_q0 => out_bufI_t_q0,
        outQ_address0 => stage_write_output_U0_outQ_address0,
        outQ_ce0 => stage_write_output_U0_outQ_ce0,
        outQ_q0 => out_bufQ_t_q0,
        out_stream_TDATA => stage_write_output_U0_out_stream_TDATA,
        out_stream_TVALID => stage_write_output_U0_out_stream_TVALID,
        out_stream_TKEEP => stage_write_output_U0_out_stream_TKEEP,
        out_stream_TSTRB => stage_write_output_U0_out_stream_TSTRB,
        out_stream_TUSER => stage_write_output_U0_out_stream_TUSER,
        out_stream_TLAST => stage_write_output_U0_out_stream_TLAST,
        out_stream_TID => stage_write_output_U0_out_stream_TID,
        out_stream_TDEST => stage_write_output_U0_out_stream_TDEST);

    scaling_schedule_c_U : component fft_1d_top_fifo_w32_d3_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_scaling_schedule_c_din,
        if_full_n => scaling_schedule_c_full_n,
        if_write => entry_proc_U0_scaling_schedule_c_write,
        if_dout => scaling_schedule_c_dout,
        if_empty_n => scaling_schedule_c_empty_n,
        if_read => stage_process_fft_real_U0_scaling_schedule_read,
        if_num_data_valid => scaling_schedule_c_num_data_valid,
        if_fifo_cap => scaling_schedule_c_fifo_cap);





    ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready <= ap_sync_Block_entry_in_bufI_wr_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_in_bufQ_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_in_bufQ <= ap_const_logic_0;
            else
                if (((Block_entry_in_bufI_wr_proc_U0_ap_done and Block_entry_in_bufI_wr_proc_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_in_bufQ <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_in_bufQ <= ap_sync_channel_write_in_bufQ;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_channel_write_out_bufQ_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_channel_write_out_bufQ <= ap_const_logic_0;
            else
                if (((stage_process_fft_real_U0_ap_done and stage_process_fft_real_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_out_bufQ <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_out_bufQ <= ap_sync_channel_write_out_bufQ;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    Block_entry_in_bufI_wr_proc_U0_ap_continue <= ap_sync_channel_write_in_bufQ;
    Block_entry_in_bufI_wr_proc_U0_ap_start <= ((ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    Block_entry_in_bufI_wr_proc_U0_in_bufQ_full_n <= in_bufQ_i_full_n;
    ap_channel_done_in_bufQ <= ((ap_sync_reg_channel_write_in_bufQ xor ap_const_logic_1) and Block_entry_in_bufI_wr_proc_U0_ap_done);
    ap_channel_done_out_bufQ <= (stage_process_fft_real_U0_ap_done and (ap_sync_reg_channel_write_out_bufQ xor ap_const_logic_1));
    ap_done <= stage_write_output_U0_ap_done;
    ap_idle <= (stage_write_output_U0_ap_idle and stage_process_fft_real_U0_ap_idle and (out_bufQ_t_empty_n xor ap_const_logic_1) and (in_bufQ_t_empty_n xor ap_const_logic_1) and entry_proc_U0_ap_idle and Block_entry_in_bufI_wr_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Block_entry_in_bufI_wr_proc_U0_ap_ready <= (ap_sync_reg_Block_entry_in_bufI_wr_proc_U0_ap_ready or Block_entry_in_bufI_wr_proc_U0_ap_ready);
    ap_sync_channel_write_in_bufQ <= ((ap_channel_done_in_bufQ and Block_entry_in_bufI_wr_proc_U0_in_bufQ_full_n) or ap_sync_reg_channel_write_in_bufQ);
    ap_sync_channel_write_out_bufQ <= ((stage_process_fft_real_U0_out_bufQ_full_n and ap_channel_done_out_bufQ) or ap_sync_reg_channel_write_out_bufQ);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc_U0_ap_ready and ap_sync_Block_entry_in_bufI_wr_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    in_stream_TREADY <= Block_entry_in_bufI_wr_proc_U0_in_stream_TREADY;
    out_stream_TDATA <= stage_write_output_U0_out_stream_TDATA;
    out_stream_TDEST <= stage_write_output_U0_out_stream_TDEST;
    out_stream_TID <= stage_write_output_U0_out_stream_TID;
    out_stream_TKEEP <= stage_write_output_U0_out_stream_TKEEP;
    out_stream_TLAST <= stage_write_output_U0_out_stream_TLAST;
    out_stream_TSTRB <= stage_write_output_U0_out_stream_TSTRB;
    out_stream_TUSER <= stage_write_output_U0_out_stream_TUSER;
    out_stream_TVALID <= stage_write_output_U0_out_stream_TVALID;
    stage_process_fft_real_U0_ap_continue <= ap_sync_channel_write_out_bufQ;
    stage_process_fft_real_U0_ap_start <= in_bufQ_t_empty_n;
    stage_process_fft_real_U0_out_bufQ_full_n <= out_bufQ_i_full_n;
    stage_write_output_U0_ap_continue <= ap_const_logic_1;
    stage_write_output_U0_ap_start <= out_bufQ_t_empty_n;
end behav;
