// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fft_1d_top_stage_process_fft_real (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        scaling_schedule_dout,
        scaling_schedule_empty_n,
        scaling_schedule_read,
        scaling_schedule_num_data_valid,
        scaling_schedule_fifo_cap,
        in_bufI_address0,
        in_bufI_ce0,
        in_bufI_q0,
        in_bufQ_address0,
        in_bufQ_ce0,
        in_bufQ_q0,
        out_bufI_address1,
        out_bufI_ce1,
        out_bufI_we1,
        out_bufI_d1,
        out_bufQ_address1,
        out_bufQ_ce1,
        out_bufQ_we1,
        out_bufQ_d1
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] scaling_schedule_dout;
input   scaling_schedule_empty_n;
output   scaling_schedule_read;
input  [2:0] scaling_schedule_num_data_valid;
input  [2:0] scaling_schedule_fifo_cap;
output  [9:0] in_bufI_address0;
output   in_bufI_ce0;
input  [15:0] in_bufI_q0;
output  [9:0] in_bufQ_address0;
output   in_bufQ_ce0;
input  [15:0] in_bufQ_q0;
output  [9:0] out_bufI_address1;
output   out_bufI_ce1;
output   out_bufI_we1;
output  [15:0] out_bufI_d1;
output  [9:0] out_bufQ_address1;
output   out_bufQ_ce1;
output   out_bufQ_we1;
output  [15:0] out_bufQ_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg scaling_schedule_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    scaling_schedule_blk_n;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_idle;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready;
wire   [31:0] grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write;
wire   [9:0] grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0;
wire   [9:0] grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0;
wire    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0;
reg    grp_fft_ZenithFFTConfig_s_fu_101_ap_ce;
wire    grp_fft_ZenithFFTConfig_s_fu_101_ap_start;
wire    grp_fft_ZenithFFTConfig_s_fu_101_ap_done;
wire    grp_fft_ZenithFFTConfig_s_fu_101_ap_idle;
wire    grp_fft_ZenithFFTConfig_s_fu_101_ap_ready;
wire    grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read;
wire   [31:0] grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din;
wire    grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write;
wire    grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_idle;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read;
wire   [9:0] grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1;
wire   [15:0] grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1;
wire   [9:0] grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1;
wire    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1;
wire   [15:0] grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1;
reg    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg;
wire   [15:0] fft_config_stream_din;
wire    fft_config_stream_full_n;
reg    fft_config_stream_write;
reg    ap_block_state1_ignore_call19;
wire    ap_CS_fsm_state2;
wire    fft_in_stream_full_n;
reg    fft_in_stream_write;
reg    grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg;
wire   [31:0] fft_in_stream_dout;
wire    fft_in_stream_empty_n;
reg    fft_in_stream_read;
wire    fft_out_stream_full_n;
reg    fft_out_stream_write;
wire   [15:0] fft_config_stream_dout;
wire    fft_config_stream_empty_n;
reg    fft_config_stream_read;
reg    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [31:0] fft_out_stream_dout;
wire    fft_out_stream_empty_n;
reg    fft_out_stream_read;
wire    ap_CS_fsm_state6;
reg    ap_block_state1;
wire   [9:0] trunc_ln350_fu_117_p1;
wire   [10:0] fft_config_fu_121_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg = 1'b0;
#0 grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg = 1'b0;
#0 grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg = 1'b0;
end

fft_1d_top_stage_process_fft_real_Pipeline_feed_loop grp_stage_process_fft_real_Pipeline_feed_loop_fu_92(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start),
    .ap_done(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done),
    .ap_idle(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_idle),
    .ap_ready(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready),
    .fft_in_stream_din(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din),
    .fft_in_stream_full_n(fft_in_stream_full_n),
    .fft_in_stream_write(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write),
    .in_bufI_address0(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0),
    .in_bufI_ce0(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0),
    .in_bufI_q0(in_bufI_q0),
    .in_bufQ_address0(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0),
    .in_bufQ_ce0(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0),
    .in_bufQ_q0(in_bufQ_q0)
);

fft_1d_top_fft_ZenithFFTConfig_s grp_fft_ZenithFFTConfig_s_fu_101(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_ce(grp_fft_ZenithFFTConfig_s_fu_101_ap_ce),
    .ap_start(grp_fft_ZenithFFTConfig_s_fu_101_ap_start),
    .ap_done(grp_fft_ZenithFFTConfig_s_fu_101_ap_done),
    .ap_idle(grp_fft_ZenithFFTConfig_s_fu_101_ap_idle),
    .ap_ready(grp_fft_ZenithFFTConfig_s_fu_101_ap_ready),
    .fft_in_stream_dout(fft_in_stream_dout),
    .fft_in_stream_empty_n(fft_in_stream_empty_n),
    .fft_in_stream_read(grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read),
    .fft_out_stream_din(grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din),
    .fft_out_stream_full_n(fft_out_stream_full_n),
    .fft_out_stream_write(grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write),
    .fft_config_stream_dout(fft_config_stream_dout),
    .fft_config_stream_empty_n(fft_config_stream_empty_n),
    .fft_config_stream_read(grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read)
);

fft_1d_top_stage_process_fft_real_Pipeline_drain_loop grp_stage_process_fft_real_Pipeline_drain_loop_fu_108(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start),
    .ap_done(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done),
    .ap_idle(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_idle),
    .ap_ready(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready),
    .fft_out_stream_dout(fft_out_stream_dout),
    .fft_out_stream_empty_n(fft_out_stream_empty_n),
    .fft_out_stream_read(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read),
    .out_bufI_address1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1),
    .out_bufI_ce1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1),
    .out_bufI_we1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1),
    .out_bufI_d1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1),
    .out_bufQ_address1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1),
    .out_bufQ_ce1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1),
    .out_bufQ_we1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1),
    .out_bufQ_d1(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1)
);

fft_1d_top_fifo_w32_d1024_A fft_in_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din),
    .if_full_n(fft_in_stream_full_n),
    .if_write(fft_in_stream_write),
    .if_dout(fft_in_stream_dout),
    .if_empty_n(fft_in_stream_empty_n),
    .if_read(fft_in_stream_read)
);

fft_1d_top_fifo_w32_d1024_A fft_out_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din),
    .if_full_n(fft_out_stream_full_n),
    .if_write(fft_out_stream_write),
    .if_dout(fft_out_stream_dout),
    .if_empty_n(fft_out_stream_empty_n),
    .if_read(fft_out_stream_read)
);

fft_1d_top_fifo_w16_d2_S fft_config_stream_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(fft_config_stream_din),
    .if_full_n(fft_config_stream_full_n),
    .if_write(fft_config_stream_write),
    .if_dout(fft_config_stream_dout),
    .if_empty_n(fft_config_stream_empty_n),
    .if_read(fft_config_stream_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state6) & (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= 1'b1;
        end else if ((grp_fft_ZenithFFTConfig_s_fu_101_ap_ready == 1'b1)) begin
            grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= 1'b1;
        end else if ((grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready == 1'b1)) begin
            grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1_ignore_call19))) begin
            grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= 1'b1;
        end else if ((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready == 1'b1)) begin
            grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fft_ZenithFFTConfig_s_fu_101_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        fft_config_stream_read = grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read;
    end else begin
        fft_config_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        fft_config_stream_write = 1'b1;
    end else begin
        fft_config_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        fft_in_stream_read = grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read;
    end else begin
        fft_in_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fft_in_stream_write = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write;
    end else begin
        fft_in_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        fft_out_stream_read = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read;
    end else begin
        fft_out_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        fft_out_stream_write = grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write;
    end else begin
        fft_out_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fft_ZenithFFTConfig_s_fu_101_ap_ce = 1'b1;
    end else begin
        grp_fft_ZenithFFTConfig_s_fu_101_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        scaling_schedule_blk_n = scaling_schedule_empty_n;
    end else begin
        scaling_schedule_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        scaling_schedule_read = 1'b1;
    end else begin
        scaling_schedule_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_fft_ZenithFFTConfig_s_fu_101_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((scaling_schedule_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (fft_config_stream_full_n == 1'b0) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call19 = ((scaling_schedule_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (fft_config_stream_full_n == 1'b0) | (ap_start == 1'b0));
end

assign fft_config_fu_121_p3 = {{trunc_ln350_fu_117_p1}, {1'd1}};

assign fft_config_stream_din = fft_config_fu_121_p3;

assign grp_fft_ZenithFFTConfig_s_fu_101_ap_start = grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg;

assign grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg;

assign grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg;

assign in_bufI_address0 = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0;

assign in_bufI_ce0 = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0;

assign in_bufQ_address0 = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0;

assign in_bufQ_ce0 = grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0;

assign out_bufI_address1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1;

assign out_bufI_ce1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1;

assign out_bufI_d1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1;

assign out_bufI_we1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1;

assign out_bufQ_address1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1;

assign out_bufQ_ce1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1;

assign out_bufQ_d1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1;

assign out_bufQ_we1 = grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1;

assign trunc_ln350_fu_117_p1 = scaling_schedule_dout[9:0];

endmodule //fft_1d_top_stage_process_fft_real
