// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module fft_1d_top_Block_entry_in_bufI_wr_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        in_bufI_address1,
        in_bufI_ce1,
        in_bufI_we1,
        in_bufI_d1,
        in_bufQ_address1,
        in_bufQ_ce1,
        in_bufQ_we1,
        in_bufQ_d1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [3:0] in_stream_TKEEP;
input  [3:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [9:0] in_bufI_address1;
output   in_bufI_ce1;
output   in_bufI_we1;
output  [15:0] in_bufI_d1;
output  [9:0] in_bufQ_address1;
output   in_bufQ_ce1;
output   in_bufQ_we1;
output  [15:0] in_bufQ_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] in_bufI_address1;
reg in_bufI_ce1;
reg in_bufI_we1;
reg[15:0] in_bufI_d1;
reg[9:0] in_bufQ_address1;
reg in_bufQ_ce1;
reg in_bufQ_we1;
reg[15:0] in_bufQ_d1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_stage_read_input_fu_50_ap_start;
wire    grp_stage_read_input_fu_50_ap_done;
wire    grp_stage_read_input_fu_50_ap_idle;
wire    grp_stage_read_input_fu_50_ap_ready;
wire    grp_stage_read_input_fu_50_in_stream_TREADY;
wire   [9:0] grp_stage_read_input_fu_50_bufI_address1;
wire    grp_stage_read_input_fu_50_bufI_ce1;
wire    grp_stage_read_input_fu_50_bufI_we1;
wire   [15:0] grp_stage_read_input_fu_50_bufI_d1;
wire   [9:0] grp_stage_read_input_fu_50_bufQ_address1;
wire    grp_stage_read_input_fu_50_bufQ_ce1;
wire    grp_stage_read_input_fu_50_bufQ_we1;
wire   [15:0] grp_stage_read_input_fu_50_bufQ_d1;
wire    grp_stage_read_input_1_fu_72_ap_start;
wire    grp_stage_read_input_1_fu_72_ap_done;
wire    grp_stage_read_input_1_fu_72_ap_idle;
wire    grp_stage_read_input_1_fu_72_ap_ready;
wire    grp_stage_read_input_1_fu_72_in_stream_TREADY;
wire   [9:0] grp_stage_read_input_1_fu_72_bufI_address1;
wire    grp_stage_read_input_1_fu_72_bufI_ce1;
wire    grp_stage_read_input_1_fu_72_bufI_we1;
wire   [15:0] grp_stage_read_input_1_fu_72_bufI_d1;
wire   [9:0] grp_stage_read_input_1_fu_72_bufQ_address1;
wire    grp_stage_read_input_1_fu_72_bufQ_ce1;
wire    grp_stage_read_input_1_fu_72_bufQ_we1;
wire   [15:0] grp_stage_read_input_1_fu_72_bufQ_d1;
reg    grp_stage_read_input_fu_50_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_stage_read_input_1_fu_72_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [4:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [31:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [3:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [3:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_user_V_U_apdone_blk;
wire   [0:0] in_stream_TUSER_int_regslice;
wire    regslice_both_in_stream_V_user_V_U_vld_out;
wire    regslice_both_in_stream_V_user_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire    regslice_both_in_stream_V_id_V_U_apdone_blk;
wire   [0:0] in_stream_TID_int_regslice;
wire    regslice_both_in_stream_V_id_V_U_vld_out;
wire    regslice_both_in_stream_V_id_V_U_ack_in;
wire    regslice_both_in_stream_V_dest_V_U_apdone_blk;
wire   [0:0] in_stream_TDEST_int_regslice;
wire    regslice_both_in_stream_V_dest_V_U_vld_out;
wire    regslice_both_in_stream_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_stage_read_input_fu_50_ap_start_reg = 1'b0;
#0 grp_stage_read_input_1_fu_72_ap_start_reg = 1'b0;
end

fft_1d_top_stage_read_input grp_stage_read_input_fu_50(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_read_input_fu_50_ap_start),
    .ap_done(grp_stage_read_input_fu_50_ap_done),
    .ap_idle(grp_stage_read_input_fu_50_ap_idle),
    .ap_ready(grp_stage_read_input_fu_50_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stage_read_input_fu_50_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice),
    .bufI_address1(grp_stage_read_input_fu_50_bufI_address1),
    .bufI_ce1(grp_stage_read_input_fu_50_bufI_ce1),
    .bufI_we1(grp_stage_read_input_fu_50_bufI_we1),
    .bufI_d1(grp_stage_read_input_fu_50_bufI_d1),
    .bufQ_address1(grp_stage_read_input_fu_50_bufQ_address1),
    .bufQ_ce1(grp_stage_read_input_fu_50_bufQ_ce1),
    .bufQ_we1(grp_stage_read_input_fu_50_bufQ_we1),
    .bufQ_d1(grp_stage_read_input_fu_50_bufQ_d1)
);

fft_1d_top_stage_read_input_1 grp_stage_read_input_1_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_stage_read_input_1_fu_72_ap_start),
    .ap_done(grp_stage_read_input_1_fu_72_ap_done),
    .ap_idle(grp_stage_read_input_1_fu_72_ap_idle),
    .ap_ready(grp_stage_read_input_1_fu_72_ap_ready),
    .in_stream_TVALID(in_stream_TVALID_int_regslice),
    .in_stream_TDATA(in_stream_TDATA_int_regslice),
    .in_stream_TREADY(grp_stage_read_input_1_fu_72_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP_int_regslice),
    .in_stream_TSTRB(in_stream_TSTRB_int_regslice),
    .in_stream_TUSER(in_stream_TUSER_int_regslice),
    .in_stream_TLAST(in_stream_TLAST_int_regslice),
    .in_stream_TID(in_stream_TID_int_regslice),
    .in_stream_TDEST(in_stream_TDEST_int_regslice),
    .bufI_address1(grp_stage_read_input_1_fu_72_bufI_address1),
    .bufI_ce1(grp_stage_read_input_1_fu_72_bufI_ce1),
    .bufI_we1(grp_stage_read_input_1_fu_72_bufI_we1),
    .bufI_d1(grp_stage_read_input_1_fu_72_bufI_d1),
    .bufQ_address1(grp_stage_read_input_1_fu_72_bufQ_address1),
    .bufQ_ce1(grp_stage_read_input_1_fu_72_bufQ_ce1),
    .bufQ_we1(grp_stage_read_input_1_fu_72_bufQ_we1),
    .bufQ_d1(grp_stage_read_input_1_fu_72_bufQ_d1)
);

fft_1d_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TUSER),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_user_V_U_ack_in),
    .data_out(in_stream_TUSER_int_regslice),
    .vld_out(regslice_both_in_stream_V_user_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_user_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TID),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_id_V_U_ack_in),
    .data_out(in_stream_TID_int_regslice),
    .vld_out(regslice_both_in_stream_V_id_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_id_V_U_apdone_blk)
);

fft_1d_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(in_stream_TDEST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_dest_V_U_ack_in),
    .data_out(in_stream_TDEST_int_regslice),
    .vld_out(regslice_both_in_stream_V_dest_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_stage_read_input_1_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_read_input_1_fu_72_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_stage_read_input_1_fu_72_ap_start_reg <= 1'b1;
        end else if ((grp_stage_read_input_1_fu_72_ap_ready == 1'b1)) begin
            grp_stage_read_input_1_fu_72_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_stage_read_input_fu_50_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_stage_read_input_fu_50_ap_start_reg <= 1'b1;
        end else if ((grp_stage_read_input_fu_50_ap_ready == 1'b1)) begin
            grp_stage_read_input_fu_50_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_read_input_fu_50_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_stage_read_input_1_fu_72_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_read_input_1_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_stage_read_input_1_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufI_address1 = grp_stage_read_input_1_fu_72_bufI_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufI_address1 = grp_stage_read_input_fu_50_bufI_address1;
    end else begin
        in_bufI_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufI_ce1 = grp_stage_read_input_1_fu_72_bufI_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufI_ce1 = grp_stage_read_input_fu_50_bufI_ce1;
    end else begin
        in_bufI_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufI_d1 = grp_stage_read_input_1_fu_72_bufI_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufI_d1 = grp_stage_read_input_fu_50_bufI_d1;
    end else begin
        in_bufI_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufI_we1 = grp_stage_read_input_1_fu_72_bufI_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufI_we1 = grp_stage_read_input_fu_50_bufI_we1;
    end else begin
        in_bufI_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufQ_address1 = grp_stage_read_input_1_fu_72_bufQ_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufQ_address1 = grp_stage_read_input_fu_50_bufQ_address1;
    end else begin
        in_bufQ_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufQ_ce1 = grp_stage_read_input_1_fu_72_bufQ_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufQ_ce1 = grp_stage_read_input_fu_50_bufQ_ce1;
    end else begin
        in_bufQ_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufQ_d1 = grp_stage_read_input_1_fu_72_bufQ_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufQ_d1 = grp_stage_read_input_fu_50_bufQ_d1;
    end else begin
        in_bufQ_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_bufQ_we1 = grp_stage_read_input_1_fu_72_bufQ_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_bufQ_we1 = grp_stage_read_input_fu_50_bufQ_we1;
    end else begin
        in_bufQ_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        in_stream_TREADY_int_regslice = grp_stage_read_input_1_fu_72_in_stream_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_stream_TREADY_int_regslice = grp_stage_read_input_fu_50_in_stream_TREADY;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_stage_read_input_fu_50_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_stage_read_input_1_fu_72_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_stage_read_input_1_fu_72_ap_start = grp_stage_read_input_1_fu_72_ap_start_reg;

assign grp_stage_read_input_fu_50_ap_start = grp_stage_read_input_fu_50_ap_start_reg;

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

endmodule //fft_1d_top_Block_entry_in_bufI_wr_proc
