// -----------------------------------------------------------------------------
// fft_1d.cpp — The Synthesizable Logic
// Annotated based on Zenith_Week3_Day1_HLS_FFT_Kernel_Design.md
// -----------------------------------------------------------------------------
// ─── RESOURCE ESTIMATE (verified — Day 2 synthesis 2026-04-21) ───────────────
// Kernel:    fft_1d_top (placeholder passthrough, no FFT math)
// Tool:      Vitis HLS 2025.2  |  Part: xc7z020clg400-2  |  Clock: 150 MHz
//
// Synthesis results from fft_1d_top_csynth.rpt:
//   BRAM_18K:  6    (3 arrays; in_bufQ dead-code eliminated, out_bufQ→1bit)
//   DSP48E1:   0    (no multiplication in placeholder)
//   LUT:       303  (2× budget headroom available)
//   FF:        156
//   II:        1    (all three pipeline loops — read, process, write)
//   Interval:  1024 cycles (DATAFLOW confirmed)
//   CP est.:   4.069 ns  |  Fmax est.: 245.76 MHz  |  Target: 150 MHz
//   Slack:     +2.601 ns  (64% headroom for Day 3 FFT butterfly math)
//
// NOTE: Day 3 changes — adding hls::fft<> will:
//   → DSP increase to ~18 (butterfly multipliers)
//   → BRAM increase to ~12 (twiddle ROM + restored Q arrays)
//   → CP increase to ~5.5–6.1 ns (still within 6.67 ns target)
// ─────────────────────────────────────────────────────────────────────────────
#include "fft_1d.hpp"

// -----------------------------------------------------------------------------
// 4.2 Why Three Separate Static Functions?
// The `static` keyword in HLS C++ means these functions have internal linkage —
// they are not visible outside this translation unit. In hardware terms: these
// functions will not be exposed as IP ports. They are internal sub-modules.
// Three functions are the prerequisite for `#pragma HLS DATAFLOW`, allowing HLS
// to schedule these calls to overlap in time (frame-level parallelism).
// -----------------------------------------------------------------------------

// Stage 1: Deserialize
// hls::stream is passed by reference, not by value. In hardware, a stream is a
// wire connection between modules. Passing by value would break at synthesis.
static void stage_read_input(hls::stream<axis_iq_t> &in_stream,
                             ap_int<16> bufI[FFT_LENGTH],
                             ap_int<16> bufQ[FFT_LENGTH]) {
  for (int i = 0; i < FFT_LENGTH; i++) {
// #pragma HLS PIPELINE II=1 directs the synthesis engine to pipeline the loop
// body: iteration N+1 starts before iteration N finishes. II=1 means accept a
// new input sample every 1 clock cycle (150 MSPS at 150 MHz).
#pragma HLS PIPELINE II = 1
    // The .read() call waits (stalls the pipeline) until TREADY is asserted by
    // the downstream module.
    axis_iq_t pkt = in_stream.read();

    // extract_i returns an ap_int<16> — a signed type. The .range(15,0)
    // operation copies bits verbatim with no rounding, because there is no
    // fractional truncation happening here.
    bufI[i] = extract_i(pkt.data);
    bufQ[i] = extract_q(pkt.data);
  }
}

// Stage 2: The Placeholder
// This stage has separate input and output buffer arguments. This satisfies the
// SPSC (Single-Producer / Single-Consumer) constraint of DATAFLOW.
// If it read from and wrote to the same buffer (in-place), it would create a
// Read-After-Write dependency with Stage 1, breaking the ping-pong mechanism.
static void stage_process_fft(ap_int<16> bufI[FFT_LENGTH],
                              ap_int<16> bufQ[FFT_LENGTH],
                              ap_int<16> outI[FFT_LENGTH],
                              ap_int<16> outQ[FFT_LENGTH],
                              ap_uint<32> scaling_schedule) {
  // Suppress compiler and HLS warnings for unused arguments.
  // In hardware terms: these signals will be present as ports on the sub-module
  // but will not be connected to any logic.
  (void)bufQ;
  (void)scaling_schedule;

  for (int i = 0; i < FFT_LENGTH; i++) {
#pragma HLS PIPELINE II = 1
    outI[i] = bufI[i];

    // Deliberately zeroing the Q output makes the testbench verification fully
    // deterministic. When C-Sim checks `out_Q != 0`, any failure unambiguously
    // means the DATAFLOW pipeline is corrupting data.
    outQ[i] = 0;
  }
}

// Stage 3: Serialize and Frame
static void stage_write_output(ap_int<16> outI[FFT_LENGTH],
                               ap_int<16> outQ[FFT_LENGTH],
                               hls::stream<axis_iq_t> &out_stream) {
  for (int i = 0; i < FFT_LENGTH; i++) {
#pragma HLS PIPELINE II = 1
    axis_iq_t pkt;
    pkt.data = pack_iq(outI[i], outQ[i]);

    // CRITICAL: TLAST is the most safety-critical signal in the write stage.
    // It tells the AXI DMA's S2MM channel: "this is the last byte of the
    // current DMA transfer." It is generated by a counter inside the PL logic
    // (i == FFT_LENGTH - 1) at 150 MHz, avoiding Clock Domain Crossing (CDC)
    // bugs.
    pkt.last = (i == FFT_LENGTH - 1) ? 1 : 0;

    // TKEEP=0xF and TSTRB=0xF marks all 4 bytes as valid data bytes.
    // The AXI DMA uses these signals to decide how many bytes to write to DDR.
    pkt.keep = 0xF;
    pkt.strb = 0xF;

    // Explicit zeros document the intent: these fields are reserved in M2 and
    // will be populated in M3+. If left unset, the synthesis tool may infer
    // them as "X".
    pkt.user = 0;
    pkt.id = 0;
    pkt.dest = 0;

    // The .write() call manages the TVALID assertion automatically.
    out_stream.write(pkt);
  }
}

// Top-Level wrapper
void fft_1d_top(hls::stream<axis_iq_t> &in_stream,
                hls::stream<axis_iq_t> &out_stream,
                ap_uint<32> scaling_schedule) {
// #pragma HLS INTERFACE is the single most important pragma in the file.
// It defines the hardware port protocol for each function argument.

// `axis` protocol for stream ports: generates TDATA, TVALID/TREADY, TLAST,
// TKEEP, etc. Makes the IP directly plug-compatible with AXI DMA MM2S/S2MM.
#pragma HLS INTERFACE axis port = in_stream
#pragma HLS INTERFACE axis port = out_stream

// `s_axilite` protocol generates a memory-mapped register accessible via the
// AXI-Lite bus. `bundle = CTRL` groups all AXI-Lite ports into a single
// AXI-Lite slave interface.
#pragma HLS INTERFACE s_axilite port = scaling_schedule bundle = CTRL

// `port = return` exposes the ap_ctrl_hs handshake registers (ap_start,
// ap_done, ap_idle). Without this, the ARM has no way to trigger the kernel.
#pragma HLS INTERFACE s_axilite port = return bundle = CTRL

  // Why are the buffers declared here, not inside the stage functions?
  // DATAFLOW ping-pong requires the buffer to be accessible to both the
  // producer stage and the consumer stage simultaneously.
  ap_int<16> in_bufI[FFT_LENGTH];
  ap_int<16> in_bufQ[FFT_LENGTH];
  ap_int<16> out_bufI[FFT_LENGTH];
  ap_int<16> out_bufQ[FFT_LENGTH];

// `RAM_2P` (Dual-Port RAM) means the BRAM block exposes two independent R/W
// ports. This is required because Stage 2 reads output data while Stage 1
// writes the next frame's input data. `impl=BRAM` forces the tool to use
// dedicated Block RAM primitives instead of LUTRAM or Registers.
#pragma HLS BIND_STORAGE variable = in_bufI type = RAM_2P impl = BRAM
#pragma HLS BIND_STORAGE variable = in_bufQ type = RAM_2P impl = BRAM
#pragma HLS BIND_STORAGE variable = out_bufI type = RAM_2P impl = BRAM
#pragma HLS BIND_STORAGE variable = out_bufQ type = RAM_2P impl = BRAM

// #pragma HLS DATAFLOW allows read, process, and write stages to be scheduled
// as a streaming pipeline (frame-level parallelism).
// It must appear between the last local declaration and the first function
// call.
#pragma HLS DATAFLOW
  stage_read_input(in_stream, in_bufI, in_bufQ);
  stage_process_fft(in_bufI, in_bufQ, out_bufI, out_bufQ, scaling_schedule);
  stage_write_output(out_bufI, out_bufQ, out_stream);
}
