

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_bufI_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_bufQ_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_bufI_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_bufQ_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.grp_stage_read_input_fu_50"},
	{"ID" : "9", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.grp_stage_read_input_fu_50.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.grp_stage_read_input_1_fu_72"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.grp_stage_read_input_1_fu_72.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_data_V_U"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_keep_V_U"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_strb_V_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_user_V_U"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_last_V_U"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_id_V_U"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_in_bufI_wr_proc_U0.regslice_both_in_stream_V_dest_V_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.grp_stage_process_fft_real_Pipeline_feed_loop_fu_92"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.grp_stage_process_fft_real_Pipeline_feed_loop_fu_92.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.grp_fft_ZenithFFTConfig_s_fu_101"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.grp_stage_process_fft_real_Pipeline_drain_loop_fu_108"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.grp_stage_process_fft_real_Pipeline_drain_loop_fu_108.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.fft_in_stream_fifo_U"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.fft_out_stream_fifo_U"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_process_fft_real_U0.fft_config_stream_fifo_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.flow_control_loop_pipe_U"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_data_V_U"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_keep_V_U"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_strb_V_U"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_user_V_U"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_last_V_U"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_id_V_U"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.stage_write_output_U0.regslice_both_out_stream_V_dest_V_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.scaling_schedule_c_U"}]}
set DependenceCheckSize 0
