// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cfar_core_cfar_core,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.639687,HLS_SYN_LAT=6,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=954,HLS_SYN_LUT=735,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module cfar_core (
        ap_clk,
        ap_rst_n,
        out_stream_TREADY,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   out_stream_TREADY;
input  [15:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [1:0] in_stream_TKEEP;
input  [1:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [15:0] out_stream_TDATA;
output   out_stream_TVALID;
output  [1:0] out_stream_TKEEP;
output  [1:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_ready;
reg   [0:0] p_vld_reg_1006;
reg   [0:0] p_vld_reg_1006_pp0_iter4_reg;
reg    ap_block_state6_pp0_stage0_iter5_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg   [0:0] p_vld_reg_1006_pp0_iter5_reg;
reg    ap_block_state7_pp0_stage0_iter6_grp1;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
wire  signed [15:0] threshold_alpha;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1;
reg   [15:0] cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0;
reg    out_stream_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
wire   [0:0] p_vld_fu_224_p1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0;
reg   [0:0] p_vld_reg_1006_pp0_iter1_reg;
reg   [0:0] p_vld_reg_1006_pp0_iter2_reg;
reg   [0:0] p_vld_reg_1006_pp0_iter3_reg;
reg   [1:0] input_sample_keep_reg_1010;
reg   [1:0] input_sample_keep_reg_1010_pp0_iter1_reg;
reg   [1:0] input_sample_keep_reg_1010_pp0_iter2_reg;
reg   [1:0] input_sample_keep_reg_1010_pp0_iter3_reg;
reg   [1:0] input_sample_keep_reg_1010_pp0_iter4_reg;
reg   [1:0] input_sample_strb_reg_1015;
reg   [1:0] input_sample_strb_reg_1015_pp0_iter1_reg;
reg   [1:0] input_sample_strb_reg_1015_pp0_iter2_reg;
reg   [1:0] input_sample_strb_reg_1015_pp0_iter3_reg;
reg   [1:0] input_sample_strb_reg_1015_pp0_iter4_reg;
reg   [0:0] input_sample_last_reg_1020;
reg   [0:0] input_sample_last_reg_1020_pp0_iter1_reg;
reg   [0:0] input_sample_last_reg_1020_pp0_iter2_reg;
reg   [0:0] input_sample_last_reg_1020_pp0_iter3_reg;
reg   [0:0] input_sample_last_reg_1020_pp0_iter4_reg;
reg   [15:0] cut_val_reg_1025;
reg   [15:0] cut_val_reg_1025_pp0_iter1_reg;
reg   [15:0] cut_val_reg_1025_pp0_iter2_reg;
reg   [15:0] cut_val_reg_1025_pp0_iter3_reg;
reg   [15:0] cut_val_reg_1025_pp0_iter4_reg;
wire   [17:0] add_ln76_2_fu_786_p2;
reg   [17:0] add_ln76_2_reg_1031;
wire   [17:0] add_ln76_5_fu_812_p2;
reg   [17:0] add_ln76_5_reg_1036;
wire   [17:0] add_ln76_9_fu_838_p2;
reg   [17:0] add_ln76_9_reg_1041;
wire   [17:0] add_ln76_12_fu_864_p2;
reg   [17:0] add_ln76_12_reg_1046;
wire   [19:0] add_ln84_fu_902_p2;
reg   [19:0] add_ln84_reg_1051;
reg   [0:0] tmp_2_reg_1056;
reg   [0:0] tmp_2_reg_1056_pp0_iter2_reg;
reg   [15:0] tmp_1_reg_1061;
reg   [15:0] tmp_1_reg_1061_pp0_iter2_reg;
reg   [15:0] tmp_reg_1066;
reg   [15:0] threshold_val_reg_1081;
wire   [0:0] empty_nbread_fu_190_p5_0;
reg    ap_block_pp0_stage0_01001_grp1;
wire  signed [15:0] input_sample_data_cast_fu_702_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0;
wire  signed [15:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0;
wire  signed [15:0] sext_ln76_fu_762_p0;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1;
wire   [16:0] add_ln76_fu_766_p2;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1;
wire   [16:0] add_ln76_1_fu_776_p2;
wire  signed [17:0] sext_ln76_2_fu_782_p1;
wire  signed [17:0] sext_ln76_1_fu_772_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1;
wire   [16:0] add_ln76_3_fu_792_p2;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1;
wire   [16:0] add_ln76_4_fu_802_p2;
wire  signed [17:0] sext_ln76_5_fu_808_p1;
wire  signed [17:0] sext_ln76_4_fu_798_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1;
wire   [16:0] add_ln76_7_fu_818_p2;
wire  signed [16:0] input_sample_data_cast_fu_702_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1;
wire   [16:0] add_ln76_8_fu_828_p2;
wire  signed [17:0] sext_ln76_9_fu_834_p1;
wire  signed [17:0] sext_ln76_8_fu_824_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1;
wire   [16:0] add_ln76_10_fu_844_p2;
wire  signed [16:0] cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1;
wire  signed [16:0] sext_ln76_fu_762_p1;
wire   [16:0] add_ln76_11_fu_854_p2;
wire  signed [17:0] sext_ln76_12_fu_860_p1;
wire  signed [17:0] sext_ln76_11_fu_850_p1;
wire  signed [18:0] sext_ln76_6_fu_873_p1;
wire  signed [18:0] sext_ln76_3_fu_870_p1;
wire   [18:0] add_ln76_6_fu_876_p2;
wire  signed [18:0] sext_ln76_13_fu_889_p1;
wire  signed [18:0] sext_ln76_10_fu_886_p1;
wire   [18:0] add_ln76_13_fu_892_p2;
wire  signed [19:0] sext_ln76_14_fu_898_p1;
wire  signed [19:0] sext_ln76_7_fu_882_p1;
wire   [21:0] shl_ln_fu_926_p3;
wire   [21:0] sub_ln84_fu_933_p2;
wire   [17:0] trunc_ln84_1_fu_939_p4;
wire   [17:0] sub_ln84_1_fu_949_p2;
wire  signed [15:0] noise_level_fu_965_p3;
wire   [23:0] grp_fu_978_p2;
wire   [0:0] icmp_ln102_fu_994_p2;
reg    grp_fu_978_ce;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to5;
reg    ap_reset_init_pp0;
reg    ap_block_pp0_stage0_11001;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [15:0] in_stream_TDATA_int_regslice;
wire    in_stream_TVALID_int_regslice;
reg    in_stream_TREADY_int_regslice;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [1:0] in_stream_TKEEP_int_regslice;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [1:0] in_stream_TSTRB_int_regslice;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int_regslice;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [15:0] out_stream_TDATA_int_regslice;
reg    out_stream_TVALID_int_regslice;
wire    out_stream_TREADY_int_regslice;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1 = 16'd0;
#0 cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0 = 16'd0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 = 1'b0;
end

cfar_core_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .threshold_alpha(threshold_alpha),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

cfar_core_mul_16s_16s_24_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 24 ))
mul_16s_16s_24_2_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(noise_level_fu_965_p3),
    .din1(threshold_alpha),
    .ce(grp_fu_978_ce),
    .dout(grp_fu_978_p2)
);

cfar_core_regslice_both #(
    .DataWidth( 16 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int_regslice),
    .vld_out(in_stream_TVALID_int_regslice),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int_regslice),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int_regslice),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int_regslice),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 16 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int_regslice),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(out_stream_TREADY_int_regslice),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_sample_keep_reg_1010_pp0_iter4_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 2 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_sample_strb_reg_1015_pp0_iter4_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

cfar_core_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(input_sample_last_reg_1020_pp0_iter4_reg),
    .vld_in(out_stream_TVALID_int_regslice),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
            ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
    end else begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln76_12_reg_1046 <= add_ln76_12_fu_864_p2;
        add_ln76_2_reg_1031 <= add_ln76_2_fu_786_p2;
        add_ln76_5_reg_1036 <= add_ln76_5_fu_812_p2;
        add_ln76_9_reg_1041 <= add_ln76_9_fu_838_p2;
        cut_val_reg_1025 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9;
        input_sample_keep_reg_1010 <= in_stream_TKEEP_int_regslice;
        input_sample_last_reg_1020 <= in_stream_TLAST_int_regslice;
        input_sample_strb_reg_1015 <= in_stream_TSTRB_int_regslice;
        p_vld_reg_1006 <= empty_nbread_fu_190_p5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln84_reg_1051 <= add_ln84_fu_902_p2;
        cut_val_reg_1025_pp0_iter1_reg <= cut_val_reg_1025;
        input_sample_keep_reg_1010_pp0_iter1_reg <= input_sample_keep_reg_1010;
        input_sample_last_reg_1020_pp0_iter1_reg <= input_sample_last_reg_1020;
        input_sample_strb_reg_1015_pp0_iter1_reg <= input_sample_strb_reg_1015;
        p_vld_reg_1006_pp0_iter1_reg <= p_vld_reg_1006;
        tmp_1_reg_1061 <= {{add_ln84_fu_902_p2[19:4]}};
        tmp_2_reg_1056 <= add_ln84_fu_902_p2[32'd19];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (p_vld_fu_224_p1 == 1'd1))) begin
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0 <= in_stream_TDATA_int_regslice;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7;
        cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        cut_val_reg_1025_pp0_iter2_reg <= cut_val_reg_1025_pp0_iter1_reg;
        cut_val_reg_1025_pp0_iter3_reg <= cut_val_reg_1025_pp0_iter2_reg;
        cut_val_reg_1025_pp0_iter4_reg <= cut_val_reg_1025_pp0_iter3_reg;
        input_sample_keep_reg_1010_pp0_iter2_reg <= input_sample_keep_reg_1010_pp0_iter1_reg;
        input_sample_keep_reg_1010_pp0_iter3_reg <= input_sample_keep_reg_1010_pp0_iter2_reg;
        input_sample_keep_reg_1010_pp0_iter4_reg <= input_sample_keep_reg_1010_pp0_iter3_reg;
        input_sample_last_reg_1020_pp0_iter2_reg <= input_sample_last_reg_1020_pp0_iter1_reg;
        input_sample_last_reg_1020_pp0_iter3_reg <= input_sample_last_reg_1020_pp0_iter2_reg;
        input_sample_last_reg_1020_pp0_iter4_reg <= input_sample_last_reg_1020_pp0_iter3_reg;
        input_sample_strb_reg_1015_pp0_iter2_reg <= input_sample_strb_reg_1015_pp0_iter1_reg;
        input_sample_strb_reg_1015_pp0_iter3_reg <= input_sample_strb_reg_1015_pp0_iter2_reg;
        input_sample_strb_reg_1015_pp0_iter4_reg <= input_sample_strb_reg_1015_pp0_iter3_reg;
        p_vld_reg_1006_pp0_iter2_reg <= p_vld_reg_1006_pp0_iter1_reg;
        p_vld_reg_1006_pp0_iter3_reg <= p_vld_reg_1006_pp0_iter2_reg;
        p_vld_reg_1006_pp0_iter4_reg <= p_vld_reg_1006_pp0_iter3_reg;
        p_vld_reg_1006_pp0_iter5_reg <= p_vld_reg_1006_pp0_iter4_reg;
        threshold_val_reg_1081 <= {{grp_fu_978_p2[23:8]}};
        tmp_1_reg_1061_pp0_iter2_reg <= tmp_1_reg_1061;
        tmp_2_reg_1056_pp0_iter2_reg <= tmp_2_reg_1056;
        tmp_reg_1066 <= {{sub_ln84_1_fu_949_p2[17:2]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_idle_pp0_0to5 == 1'b1)) begin
        ap_reset_init_pp0 = 1'b1;
    end else begin
        ap_reset_init_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1))) begin
        grp_fu_978_ce = 1'b1;
    end else begin
        grp_fu_978_ce = 1'b0;
    end
end

always @ (*) begin
    if (((in_stream_TVALID_int_regslice == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TREADY_int_regslice = 1'b1;
    end else begin
        in_stream_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((p_vld_reg_1006_pp0_iter5_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1) & (p_vld_reg_1006_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int_regslice;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (p_vld_reg_1006_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        out_stream_TVALID_int_regslice = 1'b1;
    end else begin
        out_stream_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln76_10_fu_844_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1));

assign add_ln76_11_fu_854_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1) + $signed(sext_ln76_fu_762_p1));

assign add_ln76_12_fu_864_p2 = ($signed(sext_ln76_12_fu_860_p1) + $signed(sext_ln76_11_fu_850_p1));

assign add_ln76_13_fu_892_p2 = ($signed(sext_ln76_13_fu_889_p1) + $signed(sext_ln76_10_fu_886_p1));

assign add_ln76_1_fu_776_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1));

assign add_ln76_2_fu_786_p2 = ($signed(sext_ln76_2_fu_782_p1) + $signed(sext_ln76_1_fu_772_p1));

assign add_ln76_3_fu_792_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1));

assign add_ln76_4_fu_802_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1));

assign add_ln76_5_fu_812_p2 = ($signed(sext_ln76_5_fu_808_p1) + $signed(sext_ln76_4_fu_798_p1));

assign add_ln76_6_fu_876_p2 = ($signed(sext_ln76_6_fu_873_p1) + $signed(sext_ln76_3_fu_870_p1));

assign add_ln76_7_fu_818_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1));

assign add_ln76_8_fu_828_p2 = ($signed(input_sample_data_cast_fu_702_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1));

assign add_ln76_9_fu_838_p2 = ($signed(sext_ln76_9_fu_834_p1) + $signed(sext_ln76_8_fu_824_p1));

assign add_ln76_fu_766_p2 = ($signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1) + $signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1));

assign add_ln84_fu_902_p2 = ($signed(sext_ln76_14_fu_898_p1) + $signed(sext_ln76_7_fu_882_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5_grp1)));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & ((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b1) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1)))) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5_grp1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = (((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state7_pp0_stage0_iter6_grp1)) | ((1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_pp0_stage0_iter5_grp1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5_grp1 = ((out_stream_TREADY_int_regslice == 1'b0) & (p_vld_reg_1006_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6_grp1 = ((out_stream_TREADY_int_regslice == 1'b0) & (p_vld_reg_1006_pp0_iter5_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6;

assign cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1 = cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0;

assign empty_nbread_fu_190_p5_0 = in_stream_TVALID_int_regslice;

assign icmp_ln102_fu_994_p2 = (($signed(cut_val_reg_1025_pp0_iter4_reg) > $signed(threshold_val_reg_1081)) ? 1'b1 : 1'b0);

assign in_stream_TREADY = regslice_both_in_stream_V_data_V_U_ack_in;

assign input_sample_data_cast_fu_702_p0 = in_stream_TDATA_int_regslice;

assign input_sample_data_cast_fu_702_p1 = input_sample_data_cast_fu_702_p0;

assign noise_level_fu_965_p3 = ((tmp_2_reg_1056_pp0_iter2_reg[0:0] == 1'b1) ? tmp_reg_1066 : tmp_1_reg_1061_pp0_iter2_reg);

assign out_stream_TDATA_int_regslice = ((icmp_ln102_fu_994_p2[0:0] == 1'b1) ? cut_val_reg_1025_pp0_iter4_reg : 16'd0);

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign p_vld_fu_224_p1 = empty_nbread_fu_190_p5_0;

assign sext_ln76_10_fu_886_p1 = $signed(add_ln76_9_reg_1041);

assign sext_ln76_11_fu_850_p1 = $signed(add_ln76_10_fu_844_p2);

assign sext_ln76_12_fu_860_p1 = $signed(add_ln76_11_fu_854_p2);

assign sext_ln76_13_fu_889_p1 = $signed(add_ln76_12_reg_1046);

assign sext_ln76_14_fu_898_p1 = $signed(add_ln76_13_fu_892_p2);

assign sext_ln76_1_fu_772_p1 = $signed(add_ln76_fu_766_p2);

assign sext_ln76_2_fu_782_p1 = $signed(add_ln76_1_fu_776_p2);

assign sext_ln76_3_fu_870_p1 = $signed(add_ln76_2_reg_1031);

assign sext_ln76_4_fu_798_p1 = $signed(add_ln76_3_fu_792_p2);

assign sext_ln76_5_fu_808_p1 = $signed(add_ln76_4_fu_802_p2);

assign sext_ln76_6_fu_873_p1 = $signed(add_ln76_5_reg_1036);

assign sext_ln76_7_fu_882_p1 = $signed(add_ln76_6_fu_876_p2);

assign sext_ln76_8_fu_824_p1 = $signed(add_ln76_7_fu_818_p2);

assign sext_ln76_9_fu_834_p1 = $signed(add_ln76_8_fu_828_p2);

assign sext_ln76_fu_762_p0 = cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0;

assign sext_ln76_fu_762_p1 = sext_ln76_fu_762_p0;

assign shl_ln_fu_926_p3 = {{add_ln84_reg_1051}, {2'd0}};

assign sub_ln84_1_fu_949_p2 = (18'd0 - trunc_ln84_1_fu_939_p4);

assign sub_ln84_fu_933_p2 = (22'd0 - shl_ln_fu_926_p3);

assign trunc_ln84_1_fu_939_p4 = {{sub_ln84_fu_933_p2[21:4]}};

endmodule //cfar_core
