-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1d_top_Block_entry_in_bufI_wr_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_bufI_ce1 : OUT STD_LOGIC;
    in_bufI_we1 : OUT STD_LOGIC;
    in_bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    in_bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_bufQ_ce1 : OUT STD_LOGIC;
    in_bufQ_we1 : OUT STD_LOGIC;
    in_bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fft_1d_top_Block_entry_in_bufI_wr_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_stage_read_input_fu_50_ap_start : STD_LOGIC;
    signal grp_stage_read_input_fu_50_ap_done : STD_LOGIC;
    signal grp_stage_read_input_fu_50_ap_idle : STD_LOGIC;
    signal grp_stage_read_input_fu_50_ap_ready : STD_LOGIC;
    signal grp_stage_read_input_fu_50_in_stream_TREADY : STD_LOGIC;
    signal grp_stage_read_input_fu_50_bufI_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_read_input_fu_50_bufI_ce1 : STD_LOGIC;
    signal grp_stage_read_input_fu_50_bufI_we1 : STD_LOGIC;
    signal grp_stage_read_input_fu_50_bufI_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_read_input_fu_50_bufQ_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_read_input_fu_50_bufQ_ce1 : STD_LOGIC;
    signal grp_stage_read_input_fu_50_bufQ_we1 : STD_LOGIC;
    signal grp_stage_read_input_fu_50_bufQ_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_read_input_1_fu_72_ap_start : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_ap_done : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_ap_idle : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_ap_ready : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_in_stream_TREADY : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_bufI_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_read_input_1_fu_72_bufI_ce1 : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_bufI_we1 : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_bufI_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_read_input_1_fu_72_bufQ_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_read_input_1_fu_72_bufQ_ce1 : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_bufQ_we1 : STD_LOGIC;
    signal grp_stage_read_input_1_fu_72_bufQ_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_read_input_fu_50_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_stage_read_input_1_fu_72_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TUSER_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TID_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDEST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1d_top_stage_read_input IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        bufI_ce1 : OUT STD_LOGIC;
        bufI_we1 : OUT STD_LOGIC;
        bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        bufQ_ce1 : OUT STD_LOGIC;
        bufQ_we1 : OUT STD_LOGIC;
        bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_stage_read_input_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_stream_TVALID : IN STD_LOGIC;
        in_stream_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        in_stream_TREADY : OUT STD_LOGIC;
        in_stream_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        bufI_ce1 : OUT STD_LOGIC;
        bufI_we1 : OUT STD_LOGIC;
        bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        bufQ_ce1 : OUT STD_LOGIC;
        bufQ_we1 : OUT STD_LOGIC;
        bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    grp_stage_read_input_fu_50 : component fft_1d_top_stage_read_input
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stage_read_input_fu_50_ap_start,
        ap_done => grp_stage_read_input_fu_50_ap_done,
        ap_idle => grp_stage_read_input_fu_50_ap_idle,
        ap_ready => grp_stage_read_input_fu_50_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_stage_read_input_fu_50_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        bufI_address1 => grp_stage_read_input_fu_50_bufI_address1,
        bufI_ce1 => grp_stage_read_input_fu_50_bufI_ce1,
        bufI_we1 => grp_stage_read_input_fu_50_bufI_we1,
        bufI_d1 => grp_stage_read_input_fu_50_bufI_d1,
        bufQ_address1 => grp_stage_read_input_fu_50_bufQ_address1,
        bufQ_ce1 => grp_stage_read_input_fu_50_bufQ_ce1,
        bufQ_we1 => grp_stage_read_input_fu_50_bufQ_we1,
        bufQ_d1 => grp_stage_read_input_fu_50_bufQ_d1);

    grp_stage_read_input_1_fu_72 : component fft_1d_top_stage_read_input_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stage_read_input_1_fu_72_ap_start,
        ap_done => grp_stage_read_input_1_fu_72_ap_done,
        ap_idle => grp_stage_read_input_1_fu_72_ap_idle,
        ap_ready => grp_stage_read_input_1_fu_72_ap_ready,
        in_stream_TVALID => in_stream_TVALID_int_regslice,
        in_stream_TDATA => in_stream_TDATA_int_regslice,
        in_stream_TREADY => grp_stage_read_input_1_fu_72_in_stream_TREADY,
        in_stream_TKEEP => in_stream_TKEEP_int_regslice,
        in_stream_TSTRB => in_stream_TSTRB_int_regslice,
        in_stream_TUSER => in_stream_TUSER_int_regslice,
        in_stream_TLAST => in_stream_TLAST_int_regslice,
        in_stream_TID => in_stream_TID_int_regslice,
        in_stream_TDEST => in_stream_TDEST_int_regslice,
        bufI_address1 => grp_stage_read_input_1_fu_72_bufI_address1,
        bufI_ce1 => grp_stage_read_input_1_fu_72_bufI_ce1,
        bufI_we1 => grp_stage_read_input_1_fu_72_bufI_we1,
        bufI_d1 => grp_stage_read_input_1_fu_72_bufI_d1,
        bufQ_address1 => grp_stage_read_input_1_fu_72_bufQ_address1,
        bufQ_ce1 => grp_stage_read_input_1_fu_72_bufQ_ce1,
        bufQ_we1 => grp_stage_read_input_1_fu_72_bufQ_we1,
        bufQ_d1 => grp_stage_read_input_1_fu_72_bufQ_d1);

    regslice_both_in_stream_V_data_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_user_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TUSER,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_user_V_U_ack_in,
        data_out => in_stream_TUSER_int_regslice,
        vld_out => regslice_both_in_stream_V_user_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_user_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_in_stream_V_id_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TID,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_id_V_U_ack_in,
        data_out => in_stream_TID_int_regslice,
        vld_out => regslice_both_in_stream_V_id_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_id_V_U_apdone_blk);

    regslice_both_in_stream_V_dest_V_U : component fft_1d_top_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => in_stream_TDEST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_dest_V_U_ack_in,
        data_out => in_stream_TDEST_int_regslice,
        vld_out => regslice_both_in_stream_V_dest_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_stage_read_input_1_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_stage_read_input_1_fu_72_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stage_read_input_1_fu_72_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_stage_read_input_1_fu_72_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stage_read_input_1_fu_72_ap_ready = ap_const_logic_1)) then 
                    grp_stage_read_input_1_fu_72_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_stage_read_input_fu_50_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stage_read_input_fu_50_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_stage_read_input_fu_50_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stage_read_input_fu_50_ap_ready = ap_const_logic_1)) then 
                    grp_stage_read_input_fu_50_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_stage_read_input_fu_50_ap_done, grp_stage_read_input_1_fu_72_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_stage_read_input_fu_50_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_stage_read_input_1_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_stage_read_input_fu_50_ap_done)
    begin
        if ((grp_stage_read_input_fu_50_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_stage_read_input_1_fu_72_ap_done)
    begin
        if ((grp_stage_read_input_1_fu_72_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_stage_read_input_1_fu_72_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_stage_read_input_1_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_stage_read_input_1_fu_72_ap_done, ap_CS_fsm_state5)
    begin
        if (((grp_stage_read_input_1_fu_72_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_stage_read_input_1_fu_72_ap_start <= grp_stage_read_input_1_fu_72_ap_start_reg;
    grp_stage_read_input_fu_50_ap_start <= grp_stage_read_input_fu_50_ap_start_reg;

    in_bufI_address1_assign_proc : process(grp_stage_read_input_fu_50_bufI_address1, grp_stage_read_input_1_fu_72_bufI_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufI_address1 <= grp_stage_read_input_1_fu_72_bufI_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufI_address1 <= grp_stage_read_input_fu_50_bufI_address1;
        else 
            in_bufI_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    in_bufI_ce1_assign_proc : process(grp_stage_read_input_fu_50_bufI_ce1, grp_stage_read_input_1_fu_72_bufI_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufI_ce1 <= grp_stage_read_input_1_fu_72_bufI_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufI_ce1 <= grp_stage_read_input_fu_50_bufI_ce1;
        else 
            in_bufI_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    in_bufI_d1_assign_proc : process(grp_stage_read_input_fu_50_bufI_d1, grp_stage_read_input_1_fu_72_bufI_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufI_d1 <= grp_stage_read_input_1_fu_72_bufI_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufI_d1 <= grp_stage_read_input_fu_50_bufI_d1;
        else 
            in_bufI_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    in_bufI_we1_assign_proc : process(grp_stage_read_input_fu_50_bufI_we1, grp_stage_read_input_1_fu_72_bufI_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufI_we1 <= grp_stage_read_input_1_fu_72_bufI_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufI_we1 <= grp_stage_read_input_fu_50_bufI_we1;
        else 
            in_bufI_we1 <= ap_const_logic_0;
        end if; 
    end process;


    in_bufQ_address1_assign_proc : process(grp_stage_read_input_fu_50_bufQ_address1, grp_stage_read_input_1_fu_72_bufQ_address1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufQ_address1 <= grp_stage_read_input_1_fu_72_bufQ_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufQ_address1 <= grp_stage_read_input_fu_50_bufQ_address1;
        else 
            in_bufQ_address1 <= "XXXXXXXXXX";
        end if; 
    end process;


    in_bufQ_ce1_assign_proc : process(grp_stage_read_input_fu_50_bufQ_ce1, grp_stage_read_input_1_fu_72_bufQ_ce1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufQ_ce1 <= grp_stage_read_input_1_fu_72_bufQ_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufQ_ce1 <= grp_stage_read_input_fu_50_bufQ_ce1;
        else 
            in_bufQ_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    in_bufQ_d1_assign_proc : process(grp_stage_read_input_fu_50_bufQ_d1, grp_stage_read_input_1_fu_72_bufQ_d1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufQ_d1 <= grp_stage_read_input_1_fu_72_bufQ_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufQ_d1 <= grp_stage_read_input_fu_50_bufQ_d1;
        else 
            in_bufQ_d1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    in_bufQ_we1_assign_proc : process(grp_stage_read_input_fu_50_bufQ_we1, grp_stage_read_input_1_fu_72_bufQ_we1, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_bufQ_we1 <= grp_stage_read_input_1_fu_72_bufQ_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_bufQ_we1 <= grp_stage_read_input_fu_50_bufQ_we1;
        else 
            in_bufQ_we1 <= ap_const_logic_0;
        end if; 
    end process;

    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(grp_stage_read_input_fu_50_in_stream_TREADY, grp_stage_read_input_1_fu_72_in_stream_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_stream_TREADY_int_regslice <= grp_stage_read_input_1_fu_72_in_stream_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_stream_TREADY_int_regslice <= grp_stage_read_input_fu_50_in_stream_TREADY;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

end behav;
