-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity fft_1d_top_stage_process_fft_real is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    scaling_schedule_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    scaling_schedule_empty_n : IN STD_LOGIC;
    scaling_schedule_read : OUT STD_LOGIC;
    scaling_schedule_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    scaling_schedule_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    in_bufI_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_bufI_ce0 : OUT STD_LOGIC;
    in_bufI_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    in_bufQ_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    in_bufQ_ce0 : OUT STD_LOGIC;
    in_bufQ_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    out_bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_bufI_ce1 : OUT STD_LOGIC;
    out_bufI_we1 : OUT STD_LOGIC;
    out_bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_bufQ_ce1 : OUT STD_LOGIC;
    out_bufQ_we1 : OUT STD_LOGIC;
    out_bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of fft_1d_top_stage_process_fft_real is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal scaling_schedule_blk_n : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_idle : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0 : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0 : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_ce : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_start : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_done : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_idle : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_ready : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_idle : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1 : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1 : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1 : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1 : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg : STD_LOGIC := '0';
    signal fft_config_stream_din : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_config_stream_full_n : STD_LOGIC;
    signal fft_config_stream_write : STD_LOGIC;
    signal ap_block_state1_ignore_call19 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal fft_in_stream_full_n : STD_LOGIC;
    signal fft_in_stream_write : STD_LOGIC;
    signal grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg : STD_LOGIC := '0';
    signal fft_in_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_in_stream_empty_n : STD_LOGIC;
    signal fft_in_stream_read : STD_LOGIC;
    signal fft_out_stream_full_n : STD_LOGIC;
    signal fft_out_stream_write : STD_LOGIC;
    signal fft_config_stream_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal fft_config_stream_empty_n : STD_LOGIC;
    signal fft_config_stream_read : STD_LOGIC;
    signal grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal fft_out_stream_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal fft_out_stream_empty_n : STD_LOGIC;
    signal fft_out_stream_read : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal trunc_ln350_fu_117_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal fft_config_fu_121_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component fft_1d_top_stage_process_fft_real_Pipeline_feed_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fft_in_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fft_in_stream_full_n : IN STD_LOGIC;
        fft_in_stream_write : OUT STD_LOGIC;
        in_bufI_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufI_ce0 : OUT STD_LOGIC;
        in_bufI_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        in_bufQ_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        in_bufQ_ce0 : OUT STD_LOGIC;
        in_bufQ_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_fft_ZenithFFTConfig_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_ce : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fft_in_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fft_in_stream_empty_n : IN STD_LOGIC;
        fft_in_stream_read : OUT STD_LOGIC;
        fft_out_stream_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        fft_out_stream_full_n : IN STD_LOGIC;
        fft_out_stream_write : OUT STD_LOGIC;
        fft_config_stream_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        fft_config_stream_empty_n : IN STD_LOGIC;
        fft_config_stream_read : OUT STD_LOGIC );
    end component;


    component fft_1d_top_stage_process_fft_real_Pipeline_drain_loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fft_out_stream_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        fft_out_stream_empty_n : IN STD_LOGIC;
        fft_out_stream_read : OUT STD_LOGIC;
        out_bufI_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_bufI_ce1 : OUT STD_LOGIC;
        out_bufI_we1 : OUT STD_LOGIC;
        out_bufI_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        out_bufQ_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_bufQ_ce1 : OUT STD_LOGIC;
        out_bufQ_we1 : OUT STD_LOGIC;
        out_bufQ_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component fft_1d_top_fifo_w32_d1024_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fft_1d_top_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92 : component fft_1d_top_stage_process_fft_real_Pipeline_feed_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start,
        ap_done => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done,
        ap_idle => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_idle,
        ap_ready => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready,
        fft_in_stream_din => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din,
        fft_in_stream_full_n => fft_in_stream_full_n,
        fft_in_stream_write => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write,
        in_bufI_address0 => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0,
        in_bufI_ce0 => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0,
        in_bufI_q0 => in_bufI_q0,
        in_bufQ_address0 => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0,
        in_bufQ_ce0 => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0,
        in_bufQ_q0 => in_bufQ_q0);

    grp_fft_ZenithFFTConfig_s_fu_101 : component fft_1d_top_fft_ZenithFFTConfig_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_ce => grp_fft_ZenithFFTConfig_s_fu_101_ap_ce,
        ap_start => grp_fft_ZenithFFTConfig_s_fu_101_ap_start,
        ap_done => grp_fft_ZenithFFTConfig_s_fu_101_ap_done,
        ap_idle => grp_fft_ZenithFFTConfig_s_fu_101_ap_idle,
        ap_ready => grp_fft_ZenithFFTConfig_s_fu_101_ap_ready,
        fft_in_stream_dout => fft_in_stream_dout,
        fft_in_stream_empty_n => fft_in_stream_empty_n,
        fft_in_stream_read => grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read,
        fft_out_stream_din => grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din,
        fft_out_stream_full_n => fft_out_stream_full_n,
        fft_out_stream_write => grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write,
        fft_config_stream_dout => fft_config_stream_dout,
        fft_config_stream_empty_n => fft_config_stream_empty_n,
        fft_config_stream_read => grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read);

    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108 : component fft_1d_top_stage_process_fft_real_Pipeline_drain_loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start,
        ap_done => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done,
        ap_idle => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_idle,
        ap_ready => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready,
        fft_out_stream_dout => fft_out_stream_dout,
        fft_out_stream_empty_n => fft_out_stream_empty_n,
        fft_out_stream_read => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read,
        out_bufI_address1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1,
        out_bufI_ce1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1,
        out_bufI_we1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1,
        out_bufI_d1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1,
        out_bufQ_address1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1,
        out_bufQ_ce1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1,
        out_bufQ_we1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1,
        out_bufQ_d1 => grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1);

    fft_in_stream_fifo_U : component fft_1d_top_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_din,
        if_full_n => fft_in_stream_full_n,
        if_write => fft_in_stream_write,
        if_dout => fft_in_stream_dout,
        if_empty_n => fft_in_stream_empty_n,
        if_read => fft_in_stream_read);

    fft_out_stream_fifo_U : component fft_1d_top_fifo_w32_d1024_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_din,
        if_full_n => fft_out_stream_full_n,
        if_write => fft_out_stream_write,
        if_dout => fft_out_stream_dout,
        if_empty_n => fft_out_stream_empty_n,
        if_read => fft_out_stream_read);

    fft_config_stream_fifo_U : component fft_1d_top_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => fft_config_stream_din,
        if_full_n => fft_config_stream_full_n,
        if_write => fft_config_stream_write,
        if_dout => fft_config_stream_dout,
        if_empty_n => fft_config_stream_empty_n,
        if_read => fft_config_stream_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_fft_ZenithFFTConfig_s_fu_101_ap_ready = ap_const_logic_1)) then 
                    grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_ready = ap_const_logic_1)) then 
                    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1_ignore_call19))) then 
                    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_ready = ap_const_logic_1)) then 
                    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done, grp_fft_ZenithFFTConfig_s_fu_101_ap_done, ap_CS_fsm_state4, grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state6, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_fft_ZenithFFTConfig_s_fu_101_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done)
    begin
        if ((grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_fft_ZenithFFTConfig_s_fu_101_ap_done)
    begin
        if ((grp_fft_ZenithFFTConfig_s_fu_101_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done)
    begin
        if ((grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, scaling_schedule_empty_n, fft_config_stream_full_n)
    begin
                ap_block_state1 <= ((scaling_schedule_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (fft_config_stream_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state1_ignore_call19_assign_proc : process(ap_start, ap_done_reg, scaling_schedule_empty_n, fft_config_stream_full_n)
    begin
                ap_block_state1_ignore_call19 <= ((scaling_schedule_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (fft_config_stream_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done, ap_CS_fsm_state6)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    fft_config_fu_121_p3 <= (trunc_ln350_fu_117_p1 & ap_const_lv1_1);
    fft_config_stream_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(fft_config_fu_121_p3),16));

    fft_config_stream_read_assign_proc : process(grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            fft_config_stream_read <= grp_fft_ZenithFFTConfig_s_fu_101_fft_config_stream_read;
        else 
            fft_config_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    fft_config_stream_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            fft_config_stream_write <= ap_const_logic_1;
        else 
            fft_config_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    fft_in_stream_read_assign_proc : process(grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            fft_in_stream_read <= grp_fft_ZenithFFTConfig_s_fu_101_fft_in_stream_read;
        else 
            fft_in_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    fft_in_stream_write_assign_proc : process(grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fft_in_stream_write <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_fft_in_stream_write;
        else 
            fft_in_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    fft_out_stream_read_assign_proc : process(grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            fft_out_stream_read <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_fft_out_stream_read;
        else 
            fft_out_stream_read <= ap_const_logic_0;
        end if; 
    end process;


    fft_out_stream_write_assign_proc : process(grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write, ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            fft_out_stream_write <= grp_fft_ZenithFFTConfig_s_fu_101_fft_out_stream_write;
        else 
            fft_out_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    grp_fft_ZenithFFTConfig_s_fu_101_ap_ce_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            grp_fft_ZenithFFTConfig_s_fu_101_ap_ce <= ap_const_logic_1;
        else 
            grp_fft_ZenithFFTConfig_s_fu_101_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fft_ZenithFFTConfig_s_fu_101_ap_start <= grp_fft_ZenithFFTConfig_s_fu_101_ap_start_reg;
    grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_ap_start_reg;
    grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_ap_start_reg;
    in_bufI_address0 <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_address0;
    in_bufI_ce0 <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufI_ce0;
    in_bufQ_address0 <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_address0;
    in_bufQ_ce0 <= grp_stage_process_fft_real_Pipeline_feed_loop_fu_92_in_bufQ_ce0;
    out_bufI_address1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_address1;
    out_bufI_ce1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_ce1;
    out_bufI_d1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_d1;
    out_bufI_we1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufI_we1;
    out_bufQ_address1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_address1;
    out_bufQ_ce1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_ce1;
    out_bufQ_d1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_d1;
    out_bufQ_we1 <= grp_stage_process_fft_real_Pipeline_drain_loop_fu_108_out_bufQ_we1;

    scaling_schedule_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, scaling_schedule_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            scaling_schedule_blk_n <= scaling_schedule_empty_n;
        else 
            scaling_schedule_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    scaling_schedule_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            scaling_schedule_read <= ap_const_logic_1;
        else 
            scaling_schedule_read <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln350_fu_117_p1 <= scaling_schedule_dout(10 - 1 downto 0);
end behav;
