

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
		"CDFG" : "cfar_core",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Aligned", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "6", "EstimateLatencyMin" : "6", "EstimateLatencyMax" : "6",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "1",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "in_stream_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "in_stream_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "in_stream_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "in_stream_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "in_stream"},
			{"Name" : "out_stream_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream",
				"BlockSignal" : [
					{"Name" : "out_stream_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "out_stream_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "out_stream_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "out_stream"},
			{"Name" : "threshold_alpha", "Type" : "None", "Direction" : "I"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_keep_8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_strb_8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_7", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_6", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_5", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_last_8", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.CTRL_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_16s_16s_24_2_1_U1", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_in_stream_V_last_V_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_data_V_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_keep_V_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_strb_V_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_out_stream_V_last_V_U", "Parent" : "0"}]}
