-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cfar_core is
generic (
    C_S_AXI_CTRL_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_CTRL_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    out_stream_TREADY : IN STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (1 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    out_stream_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_stream_TVALID : OUT STD_LOGIC;
    out_stream_TKEEP : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    out_stream_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    s_axi_CTRL_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_WVALID : IN STD_LOGIC;
    s_axi_CTRL_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH/8-1 downto 0);
    s_axi_CTRL_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CTRL_ADDR_WIDTH-1 downto 0);
    s_axi_CTRL_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_RREADY : IN STD_LOGIC;
    s_axi_CTRL_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CTRL_DATA_WIDTH-1 downto 0);
    s_axi_CTRL_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_CTRL_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of cfar_core is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cfar_core_cfar_core,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=6.670000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.639687,HLS_SYN_LAT=6,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=954,HLS_SYN_LUT=735,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal p_vld_reg_1006 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_reg_1006_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state6_pp0_stage0_iter5_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal p_vld_reg_1006_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state7_pp0_stage0_iter6_grp1 : BOOLEAN;
    signal regslice_both_out_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal threshold_alpha : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal out_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal p_vld_fu_224_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 : BOOLEAN := false;
    signal p_vld_reg_1006_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_reg_1006_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_vld_reg_1006_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_sample_keep_reg_1010 : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_keep_reg_1010_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_keep_reg_1010_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_keep_reg_1010_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_keep_reg_1010_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_strb_reg_1015 : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_strb_reg_1015_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_strb_reg_1015_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_strb_reg_1015_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_strb_reg_1015_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal input_sample_last_reg_1020 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_sample_last_reg_1020_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_sample_last_reg_1020_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_sample_last_reg_1020_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal input_sample_last_reg_1020_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal cut_val_reg_1025 : STD_LOGIC_VECTOR (15 downto 0);
    signal cut_val_reg_1025_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal cut_val_reg_1025_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal cut_val_reg_1025_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal cut_val_reg_1025_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln76_2_fu_786_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_2_reg_1031 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_5_fu_812_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_5_reg_1036 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_9_fu_838_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_9_reg_1041 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_12_fu_864_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln76_12_reg_1046 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln84_fu_902_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal add_ln84_reg_1051 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_2_reg_1056 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1056_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_1061 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_reg_1061_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_1066 : STD_LOGIC_VECTOR (15 downto 0);
    signal threshold_val_reg_1081 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_nbread_fu_190_p5_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal input_sample_data_cast_fu_702_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln76_fu_762_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_fu_766_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_1_fu_776_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln76_2_fu_782_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln76_1_fu_772_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_3_fu_792_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_4_fu_802_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln76_5_fu_808_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln76_4_fu_798_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_7_fu_818_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal input_sample_data_cast_fu_702_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_8_fu_828_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln76_9_fu_834_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln76_8_fu_824_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_10_fu_844_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln76_fu_762_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln76_11_fu_854_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln76_12_fu_860_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln76_11_fu_850_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal sext_ln76_6_fu_873_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln76_3_fu_870_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln76_6_fu_876_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln76_13_fu_889_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln76_10_fu_886_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln76_13_fu_892_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln76_14_fu_898_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln76_7_fu_882_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal shl_ln_fu_926_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sub_ln84_fu_933_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln84_1_fu_939_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal sub_ln84_1_fu_949_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal noise_level_fu_965_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_978_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln102_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_978_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to5 : STD_LOGIC;
    signal ap_reset_init_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal in_stream_TVALID_int_regslice : STD_LOGIC;
    signal in_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_stream_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TKEEP_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TSTRB_int_regslice : STD_LOGIC_VECTOR (1 downto 0);
    signal regslice_both_in_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal in_stream_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_in_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_in_stream_V_last_V_U_ack_in : STD_LOGIC;
    signal out_stream_TDATA_int_regslice : STD_LOGIC_VECTOR (15 downto 0);
    signal out_stream_TVALID_int_regslice : STD_LOGIC;
    signal out_stream_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_stream_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_out_stream_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cfar_core_mul_16s_16s_24_2_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component cfar_core_CTRL_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        threshold_alpha : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component cfar_core_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    CTRL_s_axi_U : component cfar_core_CTRL_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CTRL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CTRL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_CTRL_AWVALID,
        AWREADY => s_axi_CTRL_AWREADY,
        AWADDR => s_axi_CTRL_AWADDR,
        WVALID => s_axi_CTRL_WVALID,
        WREADY => s_axi_CTRL_WREADY,
        WDATA => s_axi_CTRL_WDATA,
        WSTRB => s_axi_CTRL_WSTRB,
        ARVALID => s_axi_CTRL_ARVALID,
        ARREADY => s_axi_CTRL_ARREADY,
        ARADDR => s_axi_CTRL_ARADDR,
        RVALID => s_axi_CTRL_RVALID,
        RREADY => s_axi_CTRL_RREADY,
        RDATA => s_axi_CTRL_RDATA,
        RRESP => s_axi_CTRL_RRESP,
        BVALID => s_axi_CTRL_BVALID,
        BREADY => s_axi_CTRL_BREADY,
        BRESP => s_axi_CTRL_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        threshold_alpha => threshold_alpha,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    mul_16s_16s_24_2_1_U1 : component cfar_core_mul_16s_16s_24_2_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 24)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        din0 => noise_level_fu_965_p3,
        din1 => threshold_alpha,
        ce => grp_fu_978_ce,
        dout => grp_fu_978_p2);

    regslice_both_in_stream_V_data_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TDATA,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_data_V_U_ack_in,
        data_out => in_stream_TDATA_int_regslice,
        vld_out => in_stream_TVALID_int_regslice,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_data_V_U_apdone_blk);

    regslice_both_in_stream_V_keep_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TKEEP,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_keep_V_U_ack_in,
        data_out => in_stream_TKEEP_int_regslice,
        vld_out => regslice_both_in_stream_V_keep_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_keep_V_U_apdone_blk);

    regslice_both_in_stream_V_strb_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TSTRB,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_strb_V_U_ack_in,
        data_out => in_stream_TSTRB_int_regslice,
        vld_out => regslice_both_in_stream_V_strb_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_strb_V_U_apdone_blk);

    regslice_both_in_stream_V_last_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_stream_TLAST,
        vld_in => in_stream_TVALID,
        ack_in => regslice_both_in_stream_V_last_V_U_ack_in,
        data_out => in_stream_TLAST_int_regslice,
        vld_out => regslice_both_in_stream_V_last_V_U_vld_out,
        ack_out => in_stream_TREADY_int_regslice,
        apdone_blk => regslice_both_in_stream_V_last_V_U_apdone_blk);

    regslice_both_out_stream_V_data_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_stream_TDATA_int_regslice,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => out_stream_TREADY_int_regslice,
        data_out => out_stream_TDATA,
        vld_out => regslice_both_out_stream_V_data_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_data_V_U_apdone_blk);

    regslice_both_out_stream_V_keep_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_sample_keep_reg_1010_pp0_iter4_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_keep_V_U_ack_in_dummy,
        data_out => out_stream_TKEEP,
        vld_out => regslice_both_out_stream_V_keep_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_keep_V_U_apdone_blk);

    regslice_both_out_stream_V_strb_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 2)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_sample_strb_reg_1015_pp0_iter4_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_strb_V_U_ack_in_dummy,
        data_out => out_stream_TSTRB,
        vld_out => regslice_both_out_stream_V_strb_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_strb_V_U_apdone_blk);

    regslice_both_out_stream_V_last_V_U : component cfar_core_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => input_sample_last_reg_1020_pp0_iter4_reg,
        vld_in => out_stream_TVALID_int_regslice,
        ack_in => regslice_both_out_stream_V_last_V_U_ack_in_dummy,
        data_out => out_stream_TLAST,
        vld_out => regslice_both_out_stream_V_last_V_U_vld_out,
        ack_out => out_stream_TREADY,
        apdone_blk => regslice_both_out_stream_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
            else
                if ((ap_enable_reg_pp0_iter0 = ap_const_logic_1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg_iter0 <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln76_12_reg_1046 <= add_ln76_12_fu_864_p2;
                add_ln76_2_reg_1031 <= add_ln76_2_fu_786_p2;
                add_ln76_5_reg_1036 <= add_ln76_5_fu_812_p2;
                add_ln76_9_reg_1041 <= add_ln76_9_fu_838_p2;
                cut_val_reg_1025 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9;
                input_sample_keep_reg_1010 <= in_stream_TKEEP_int_regslice;
                input_sample_last_reg_1020 <= in_stream_TLAST_int_regslice;
                input_sample_strb_reg_1015 <= in_stream_TSTRB_int_regslice;
                p_vld_reg_1006 <= empty_nbread_fu_190_p5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln84_reg_1051 <= add_ln84_fu_902_p2;
                cut_val_reg_1025_pp0_iter1_reg <= cut_val_reg_1025;
                input_sample_keep_reg_1010_pp0_iter1_reg <= input_sample_keep_reg_1010;
                input_sample_last_reg_1020_pp0_iter1_reg <= input_sample_last_reg_1020;
                input_sample_strb_reg_1015_pp0_iter1_reg <= input_sample_strb_reg_1015;
                p_vld_reg_1006_pp0_iter1_reg <= p_vld_reg_1006;
                tmp_1_reg_1061 <= add_ln84_fu_902_p2(19 downto 4);
                tmp_2_reg_1056 <= add_ln84_fu_902_p2(19 downto 19);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (p_vld_fu_224_p1 = ap_const_lv1_1))) then
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0 <= in_stream_TDATA_int_regslice;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_10;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_11;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_7;
                cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_9 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                cut_val_reg_1025_pp0_iter2_reg <= cut_val_reg_1025_pp0_iter1_reg;
                cut_val_reg_1025_pp0_iter3_reg <= cut_val_reg_1025_pp0_iter2_reg;
                cut_val_reg_1025_pp0_iter4_reg <= cut_val_reg_1025_pp0_iter3_reg;
                input_sample_keep_reg_1010_pp0_iter2_reg <= input_sample_keep_reg_1010_pp0_iter1_reg;
                input_sample_keep_reg_1010_pp0_iter3_reg <= input_sample_keep_reg_1010_pp0_iter2_reg;
                input_sample_keep_reg_1010_pp0_iter4_reg <= input_sample_keep_reg_1010_pp0_iter3_reg;
                input_sample_last_reg_1020_pp0_iter2_reg <= input_sample_last_reg_1020_pp0_iter1_reg;
                input_sample_last_reg_1020_pp0_iter3_reg <= input_sample_last_reg_1020_pp0_iter2_reg;
                input_sample_last_reg_1020_pp0_iter4_reg <= input_sample_last_reg_1020_pp0_iter3_reg;
                input_sample_strb_reg_1015_pp0_iter2_reg <= input_sample_strb_reg_1015_pp0_iter1_reg;
                input_sample_strb_reg_1015_pp0_iter3_reg <= input_sample_strb_reg_1015_pp0_iter2_reg;
                input_sample_strb_reg_1015_pp0_iter4_reg <= input_sample_strb_reg_1015_pp0_iter3_reg;
                p_vld_reg_1006_pp0_iter2_reg <= p_vld_reg_1006_pp0_iter1_reg;
                p_vld_reg_1006_pp0_iter3_reg <= p_vld_reg_1006_pp0_iter2_reg;
                p_vld_reg_1006_pp0_iter4_reg <= p_vld_reg_1006_pp0_iter3_reg;
                p_vld_reg_1006_pp0_iter5_reg <= p_vld_reg_1006_pp0_iter4_reg;
                threshold_val_reg_1081 <= grp_fu_978_p2(23 downto 8);
                tmp_1_reg_1061_pp0_iter2_reg <= tmp_1_reg_1061;
                tmp_2_reg_1056_pp0_iter2_reg <= tmp_2_reg_1056;
                tmp_reg_1066 <= sub_ln84_1_fu_949_p2(17 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_init_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln76_10_fu_844_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1));
    add_ln76_11_fu_854_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1) + signed(sext_ln76_fu_762_p1));
    add_ln76_12_fu_864_p2 <= std_logic_vector(signed(sext_ln76_12_fu_860_p1) + signed(sext_ln76_11_fu_850_p1));
    add_ln76_13_fu_892_p2 <= std_logic_vector(signed(sext_ln76_13_fu_889_p1) + signed(sext_ln76_10_fu_886_p1));
    add_ln76_1_fu_776_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1));
    add_ln76_2_fu_786_p2 <= std_logic_vector(signed(sext_ln76_2_fu_782_p1) + signed(sext_ln76_1_fu_772_p1));
    add_ln76_3_fu_792_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1));
    add_ln76_4_fu_802_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1));
    add_ln76_5_fu_812_p2 <= std_logic_vector(signed(sext_ln76_5_fu_808_p1) + signed(sext_ln76_4_fu_798_p1));
    add_ln76_6_fu_876_p2 <= std_logic_vector(signed(sext_ln76_6_fu_873_p1) + signed(sext_ln76_3_fu_870_p1));
    add_ln76_7_fu_818_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1));
    add_ln76_8_fu_828_p2 <= std_logic_vector(signed(input_sample_data_cast_fu_702_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1));
    add_ln76_9_fu_838_p2 <= std_logic_vector(signed(sext_ln76_9_fu_834_p1) + signed(sext_ln76_8_fu_824_p1));
    add_ln76_fu_766_p2 <= std_logic_vector(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1) + signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1));
    add_ln84_fu_902_p2 <= std_logic_vector(signed(sext_ln76_14_fu_898_p1) + signed(sext_ln76_7_fu_882_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state6_pp0_stage0_iter5_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5_grp1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state6_pp0_stage0_iter5_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state7_pp0_stage0_iter6_grp1, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5_grp1)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state6_pp0_stage0_iter5_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5_grp1)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state6_pp0_stage0_iter5_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state7_pp0_stage0_iter6_grp1, regslice_both_out_stream_V_data_V_U_apdone_blk)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and ((regslice_both_out_stream_V_data_V_U_apdone_blk = ap_const_logic_1) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5_grp1)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_block_state6_pp0_stage0_iter5_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state7_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state7_pp0_stage0_iter6_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_pp0_stage0_iter5_grp1)));
    end process;


    ap_block_state6_pp0_stage0_iter5_grp1_assign_proc : process(p_vld_reg_1006_pp0_iter4_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state6_pp0_stage0_iter5_grp1 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (p_vld_reg_1006_pp0_iter4_reg = ap_const_lv1_1));
    end process;


    ap_block_state7_pp0_stage0_iter6_grp1_assign_proc : process(p_vld_reg_1006_pp0_iter5_reg, out_stream_TREADY_int_regslice)
    begin
                ap_block_state7_pp0_stage0_iter6_grp1 <= ((out_stream_TREADY_int_regslice = ap_const_logic_0) and (p_vld_reg_1006_pp0_iter5_reg = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to5_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to5 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_init_pp0_assign_proc : process(ap_idle_pp0_0to5)
    begin
        if ((ap_idle_pp0_0to5 = ap_const_logic_1)) then 
            ap_reset_init_pp0 <= ap_const_logic_1;
        else 
            ap_reset_init_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_12;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_12_load_cast_fu_734_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_13;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_13_load_cast_fu_730_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_14;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_14_load_cast_fu_726_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_15;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_15_load_cast_fu_722_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_16;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_16_load_cast_fu_718_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_17;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_17_load_cast_fu_714_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_18;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_18_load_cast_fu_710_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_19;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_19_load_cast_fu_706_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_1;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_1_load_cast_fu_758_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_2;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_2_load_cast_fu_754_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_3;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_3_load_cast_fu_750_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_4;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_4_load_cast_fu_746_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_5;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_5_load_cast_fu_742_p0),17));

    cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_6;
        cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cfar_core_stream_stream_ap_fixed_16_8_5_3_0_window_data_6_load_cast_fu_738_p0),17));

    empty_nbread_fu_190_p5_0 <= (0=>(in_stream_TVALID_int_regslice), others=>'-');

    grp_fu_978_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            grp_fu_978_ce <= ap_const_logic_1;
        else 
            grp_fu_978_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln102_fu_994_p2 <= "1" when (signed(cut_val_reg_1025_pp0_iter4_reg) > signed(threshold_val_reg_1081)) else "0";
    in_stream_TREADY <= regslice_both_in_stream_V_data_V_U_ack_in;

    in_stream_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001_grp1, ap_block_pp0_stage0_subdone_grp1_done_reg_iter0, in_stream_TVALID_int_regslice)
    begin
        if (((in_stream_TVALID_int_regslice = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg_iter0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TREADY_int_regslice <= ap_const_logic_1;
        else 
            in_stream_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    input_sample_data_cast_fu_702_p0 <= in_stream_TDATA_int_regslice;
        input_sample_data_cast_fu_702_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(input_sample_data_cast_fu_702_p0),17));

    noise_level_fu_965_p3 <= 
        tmp_reg_1066 when (tmp_2_reg_1056_pp0_iter2_reg(0) = '1') else 
        tmp_1_reg_1061_pp0_iter2_reg;

    out_stream_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, p_vld_reg_1006_pp0_iter4_reg, ap_block_pp0_stage0_subdone_grp1_done_reg, p_vld_reg_1006_pp0_iter5_reg, ap_block_pp0_stage0_grp1, out_stream_TREADY_int_regslice)
    begin
        if ((((p_vld_reg_1006_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (p_vld_reg_1006_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)))) then 
            out_stream_TDATA_blk_n <= out_stream_TREADY_int_regslice;
        else 
            out_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    out_stream_TDATA_int_regslice <= 
        cut_val_reg_1025_pp0_iter4_reg when (icmp_ln102_fu_994_p2(0) = '1') else 
        ap_const_lv16_0;
    out_stream_TVALID <= regslice_both_out_stream_V_data_V_U_vld_out;

    out_stream_TVALID_int_regslice_assign_proc : process(ap_enable_reg_pp0_iter5, p_vld_reg_1006_pp0_iter4_reg, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (p_vld_reg_1006_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            out_stream_TVALID_int_regslice <= ap_const_logic_1;
        else 
            out_stream_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    p_vld_fu_224_p1 <= empty_nbread_fu_190_p5_0;
        sext_ln76_10_fu_886_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_9_reg_1041),19));

        sext_ln76_11_fu_850_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_10_fu_844_p2),18));

        sext_ln76_12_fu_860_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_11_fu_854_p2),18));

        sext_ln76_13_fu_889_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_12_reg_1046),19));

        sext_ln76_14_fu_898_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_13_fu_892_p2),20));

        sext_ln76_1_fu_772_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_fu_766_p2),18));

        sext_ln76_2_fu_782_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_1_fu_776_p2),18));

        sext_ln76_3_fu_870_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_2_reg_1031),19));

        sext_ln76_4_fu_798_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_3_fu_792_p2),18));

        sext_ln76_5_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_4_fu_802_p2),18));

        sext_ln76_6_fu_873_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_5_reg_1036),19));

        sext_ln76_7_fu_882_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_6_fu_876_p2),20));

        sext_ln76_8_fu_824_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_7_fu_818_p2),18));

        sext_ln76_9_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln76_8_fu_828_p2),18));

    sext_ln76_fu_762_p0 <= cfar_core_stream_stream_axis_0_ap_fixed_16_8_5_3_0_window_data_0;
        sext_ln76_fu_762_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln76_fu_762_p0),17));

    shl_ln_fu_926_p3 <= (add_ln84_reg_1051 & ap_const_lv2_0);
    sub_ln84_1_fu_949_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(trunc_ln84_1_fu_939_p4));
    sub_ln84_fu_933_p2 <= std_logic_vector(unsigned(ap_const_lv22_0) - unsigned(shl_ln_fu_926_p3));
    trunc_ln84_1_fu_939_p4 <= sub_ln84_fu_933_p2(21 downto 4);
end behav;
